use zc::store::{Bundle, Metadata, Store, storage_id};

#[test]
fn managed_publish_is_immutable_and_uses_zig_identity() {
    assert_eq!(
        storage_id("home"),
        "dc3fb855b586386498f9ec0db774a3d31da4003977fcbcd9a697fb7455a6645b"
    );
    let temp = tempfile::tempdir().unwrap();
    let store = Store::open(temp.path().join("state")).unwrap();
    let initial = store.load().unwrap();
    let bundle = Bundle::from_memory(b"mixed-port: 9000\n", None, Default::default()).unwrap();
    let receipt = store
        .publish(
            &initial.token,
            "home",
            None,
            &bundle,
            Metadata::default(),
            true,
        )
        .unwrap();
    let loaded = store.load().unwrap();
    assert_eq!(loaded.token, receipt.token);
    let profile = store.get("home").unwrap();
    assert_eq!(
        store
            .read_bundle("home", &profile.head)
            .unwrap()
            .bundle
            .source(),
        b"mixed-port: 9000\n"
    );
    assert!(
        store
            .publish(
                &initial.token,
                "other",
                None,
                &bundle,
                Metadata::default(),
                false
            )
            .is_err()
    );
    assert_eq!(store.list().unwrap().len(), 1);
}

// Generated by Zig 0.16.0 using the repository's actual RevisionStore.publishMigration
// and config_catalog.encodeCanonical, not by the Rust encoder. Source: b"mixed-port: 9000\n".
const ZIG_MANIFEST: &str = concat!(
    r#"{"schema_version":1,"key":"home","storage_id":"dc3fb855b586386498f9ec0db774a3d31da4003977fcbcd9a697fb7455a6645b","revision":"85eae890e91da1c27aa2081ace7302b2","content_digest":"d9fba046d4f42704dc2ac58a619629b2061599bdf17b2fdfec67f0a990b131c5","metadata":{"url":null,"filename":null,"params":[]},"override":null,"source":{"size":17,"sha256":"1a0d9cbe3966156e2d2c94a3e7211e147097950cc2fa46fc496254348f9882ff"},"materialized_source":null,"aggregate_bytes":17,"local_assets":[],"remote_providers":[]}"#,
    "\n"
);
const ZIG_STATE: &str = concat!(
    r#"{"schema_version":2,"sequence":7,"active":{"key":"home","revision":"85eae890e91da1c27aa2081ace7302b2"},"profiles":[{"key":"home","storage_id":"dc3fb855b586386498f9ec0db774a3d31da4003977fcbcd9a697fb7455a6645b","head":"85eae890e91da1c27aa2081ace7302b2","desired":{"generation":0,"selections":[]}}]}"#,
    "\n"
);
const IDENTITY: &str = concat!(
    r#"{"schema_version":1,"key":"home","storage_id":"dc3fb855b586386498f9ec0db774a3d31da4003977fcbcd9a697fb7455a6645b"}"#,
    "\n"
);
const GOLDEN_REVISION: &str = "85eae890e91da1c27aa2081ace7302b2";
fn install_golden(root: &std::path::Path) {
    let dir = zc::fsutil::SecureDir::create(root).unwrap();
    let p = dir
        .child("profiles", true)
        .unwrap()
        .child(&storage_id("home"), true)
        .unwrap();
    p.write_new("identity.json", IDENTITY.as_bytes()).unwrap();
    let r = p
        .child("revisions", true)
        .unwrap()
        .child(GOLDEN_REVISION, true)
        .unwrap();
    r.child("objects", true).unwrap();
    r.write_new("source.yaml", b"mixed-port: 9000\n").unwrap();
    r.write_new("manifest.json", ZIG_MANIFEST.as_bytes())
        .unwrap();
    dir.write_new("state-v2.json", ZIG_STATE.as_bytes())
        .unwrap();
}

#[test]
fn reads_actual_zig_revision_and_emits_identical_manifest() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("zig");
    install_golden(&root);
    let store = Store::open(&root).unwrap();
    assert_eq!(store.load().unwrap().catalog.sequence, 7);
    let view = store.read_bundle("home", GOLDEN_REVISION).unwrap();
    assert_eq!(
        view.content_digest,
        "d9fba046d4f42704dc2ac58a619629b2061599bdf17b2fdfec67f0a990b131c5"
    );
    let rust_root = temp.path().join("rust");
    let rust_store = Store::open(&rust_root).unwrap();
    rust_store
        .publish(
            &rust_store.load().unwrap().token,
            "home",
            None,
            &view.bundle,
            view.metadata,
            true,
        )
        .unwrap();
    assert_eq!(rust_store.get("home").unwrap().head, GOLDEN_REVISION);
    assert_eq!(
        std::fs::read_to_string(rust_root.join(format!(
            "profiles/{}/revisions/{}/manifest.json",
            storage_id("home"),
            GOLDEN_REVISION
        )))
        .unwrap(),
        ZIG_MANIFEST
    );
}

#[test]
fn corruption_and_unknown_formats_never_reinitialize_authority() {
    use zc::store::StoreError;
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("state");
    let store = Store::open(&root).unwrap();
    let dir = zc::fsutil::SecureDir::open(&root).unwrap();
    for bytes in [
        b"".as_slice(),
        b"{}",
        b"{broken",
        b"{\"schema_version\":99}",
        b"{\"schema_version\":1,\"sequence\":3,\"profiles\":[],\"unknown\":true}",
    ] {
        dir.atomic_write("state-v2.json", bytes).unwrap();
        let error = store.load().unwrap_err();
        if bytes == b"{\"schema_version\":99}" {
            assert_eq!(
                error.downcast_ref::<StoreError>(),
                Some(&StoreError::UnknownFormat(99))
            );
        }
        assert_eq!(std::fs::read(root.join("state-v2.json")).unwrap(), bytes);
    }
    dir.remove_file("state-v2.json").unwrap();
    dir.write_new("meta.json", b"{\"active\":\"old\",\"configs\":{}}")
        .unwrap();
    assert!(
        store
            .load()
            .unwrap_err()
            .to_string()
            .contains("LegacyActiveMissing")
    );
}

#[test]
fn golden_corruption_is_not_repaired_by_republication() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("state");
    install_golden(&root);
    let store = Store::open(&root).unwrap();
    let token = store.load().unwrap().token;
    let source = root.join(format!(
        "profiles/{}/revisions/{}/source.yaml",
        storage_id("home"),
        GOLDEN_REVISION
    ));
    std::fs::write(&source, b"mixed-port: 9001\n").unwrap();
    assert!(store.load().is_err());
    let bundle = Bundle::from_memory(b"mixed-port: 9000\n", None, Default::default()).unwrap();
    assert!(
        store
            .publish(
                &token,
                "home",
                Some(GOLDEN_REVISION),
                &bundle,
                Metadata::default(),
                true
            )
            .is_err()
    );
    assert_eq!(
        std::fs::read_to_string(root.join("state-v2.json")).unwrap(),
        ZIG_STATE
    );
}

#[test]
fn selection_rename_delete_and_activation_are_cas_transactions() {
    use zc::store::Selection;
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("state");
    install_golden(&root);
    let store = Store::open(&root).unwrap();
    let before = store.load().unwrap();
    let selected = store
        .select(
            &before.token,
            "home",
            GOLDEN_REVISION,
            0,
            vec![Selection {
                group: "route".into(),
                proxy: "DIRECT".into(),
            }],
        )
        .unwrap();
    assert_eq!(store.get("home").unwrap().desired.generation, 1);
    assert!(
        store
            .select(&selected.token, "home", GOLDEN_REVISION, 0, vec![])
            .is_err()
    );
    let renamed = store
        .rename(&selected.token, "home", GOLDEN_REVISION, "office")
        .unwrap();
    let p = store.get("office").unwrap();
    assert_ne!(p.head, GOLDEN_REVISION);
    assert_eq!(p.desired.generation, 1);
    assert_eq!(store.load().unwrap().catalog.active.unwrap().key, "office");
    assert!(store.read_bundle("home", GOLDEN_REVISION).is_ok());
    let deactivated = store.activate(&renamed.token, None).unwrap();
    let activated = store.activate(&deactivated.token, Some("office")).unwrap();
    store.delete(&activated.token, "office", &p.head).unwrap();
    assert!(store.list().unwrap().is_empty());
    assert!(store.load().unwrap().catalog.active.is_none());
}

#[test]
fn immutable_assets_survive_source_deletion_and_reject_escape() {
    let temp = tempfile::tempdir().unwrap();
    let source = temp.path().join("input");
    std::fs::create_dir(&source).unwrap();
    let yaml = b"mixed-port: 9000\nrule-providers:\n  local:\n    type: file\n    behavior: domain\n    path: rules.yaml\nrules:\n  - RULE-SET,local,DIRECT\n  - MATCH,DIRECT\n";
    std::fs::write(source.join("config.yaml"), yaml).unwrap();
    std::fs::write(source.join("rules.yaml"), b"payload:\n  - example.com\n").unwrap();
    let bundle = Bundle::capture(source.join("config.yaml")).unwrap();
    let store = Store::open(temp.path().join("state")).unwrap();
    store
        .publish(
            &store.load().unwrap().token,
            "home",
            None,
            &bundle,
            Metadata::default(),
            true,
        )
        .unwrap();
    std::fs::remove_dir_all(&source).unwrap();
    let p = store.get("home").unwrap();
    let view = store.read_bundle("home", &p.head).unwrap();
    assert_eq!(
        view.bundle.resolve_local("rules.yaml").unwrap(),
        b"payload:\n  - example.com\n"
    );
    assert!(view.bundle.runtime_config().is_ok());
    std::fs::create_dir(&source).unwrap();
    std::fs::write(
        source.join("config.yaml"),
        String::from_utf8(yaml.to_vec())
            .unwrap()
            .replace("rules.yaml", "../outside.yaml"),
    )
    .unwrap();
    std::fs::write(temp.path().join("outside.yaml"), b"payload: []\n").unwrap();
    assert!(Bundle::capture(source.join("config.yaml")).is_err());
}

// Also emitted by the real Zig publisher: sorted metadata, frozen invocation,
// original/materialized sources, and a content-addressed local provider object.
const ZIG_FROZEN_MANIFEST: &str = concat!(
    r#"{"schema_version":1,"key":"home","storage_id":"dc3fb855b586386498f9ec0db774a3d31da4003977fcbcd9a697fb7455a6645b","revision":"e0fe8f011221e20d138e35a87858c502","content_digest":"c9be885b3e5176ef1d4bd3991fba96750d8e45c9d618e1f4dbe2dc7a06a5881b","metadata":{"url":"https://example.com/sub","filename":"Home","params":[{"key":"a","value":"2"},{"key":"z","value":"1"}]},"override":{"script_name":"apply.lua","script":{"size":10,"sha256":"1232d8379de77e154ca533689af2e42629dd7574bda5a0a390799849f07607c3"},"command":"config override","config_path":"configs/home.yaml","timeout_ms":500,"args":[{"key":"region","value":"hk"}],"patch":{"size":17,"sha256":"1a0d9cbe3966156e2d2c94a3e7211e147097950cc2fa46fc496254348f9882ff"}},"source":{"size":17,"sha256":"28a0fb72799922f5183e4d4ddf4b06a9423d922ec5f5fc54d888cfa0e56699b4"},"materialized_source":{"size":132,"sha256":"02b5775862e6917f121cf6bf9897df3b325c0545052a3fae7aafe34b3e93ebba"},"aggregate_bytes":174,"local_assets":[{"logical_path":"rules.yaml","canonical_relative_target":"nested/rules.yaml","object_id":"b6ff650ef958865aee9bf069bf84dd31697d8b8f5f6452e27afb5b3c90a370c2","size":25,"sha256":"b6ff650ef958865aee9bf069bf84dd31697d8b8f5f6452e27afb5b3c90a370c2"}],"remote_providers":[]}"#,
    "\n"
);

#[test]
fn reads_zig_frozen_override_asset_and_metadata_fixture() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("state");
    let dir = zc::fsutil::SecureDir::create(&root).unwrap();
    let p = dir
        .child("profiles", true)
        .unwrap()
        .child(&storage_id("home"), true)
        .unwrap();
    p.write_new("identity.json", IDENTITY.as_bytes()).unwrap();
    let r = p
        .child("revisions", true)
        .unwrap()
        .child("e0fe8f011221e20d138e35a87858c502", true)
        .unwrap();
    r.write_new("manifest.json", ZIG_FROZEN_MANIFEST.as_bytes())
        .unwrap();
    r.write_new("source.yaml", b"mixed-port: 9001\n").unwrap();
    r.write_new("materialized.yaml",b"mixed-port: 9000\nrule-providers:\n  local:\n    type: file\n    behavior: domain\n    path: rules.yaml\nrules:\n  - RULE-SET,local,DIRECT\n").unwrap();
    r.write_new("override-script", b"return {}\n").unwrap();
    r.write_new("override-output.yaml", b"mixed-port: 9000\n")
        .unwrap();
    r.child("objects", true)
        .unwrap()
        .write_new(
            "b6ff650ef958865aee9bf069bf84dd31697d8b8f5f6452e27afb5b3c90a370c2",
            b"payload:\n  - example.com\n",
        )
        .unwrap();
    let store = Store::open(&root).unwrap();
    let view = store
        .read_bundle("home", "e0fe8f011221e20d138e35a87858c502")
        .unwrap();
    assert_eq!(
        view.metadata.url.as_deref(),
        Some("https://example.com/sub")
    );
    assert_eq!(view.bundle.source(), b"mixed-port: 9001\n");
    assert_eq!(
        view.bundle.assets()["rules.yaml"].canonical_relative_target,
        "nested/rules.yaml"
    );
    let frozen = view.frozen_override.unwrap();
    assert_eq!(frozen.args[0].value, "hk");
    assert_eq!(frozen.patch_bytes, b"mixed-port: 9000\n");
    r.atomic_write("override-script", b"return 42\n").unwrap();
    assert!(
        store
            .read_bundle("home", "e0fe8f011221e20d138e35a87858c502")
            .is_err()
    );
}

#[test]
fn raw_ss_plugin_recovery_is_inactive_and_other_errors_are_rejected() {
    let source = b"mixed-port: 9000\nproxies:\n  - {name: edge, type: ss, server: 127.0.0.1, port: 443, cipher: aes-128-gcm, password: secret, plugin: unsupported}\n";
    let bundle = Bundle::from_memory(source, None, Default::default()).unwrap();
    assert!(!bundle.catalog_ready().unwrap());
    let temp = tempfile::tempdir().unwrap();
    let store = Store::open(temp.path().join("state")).unwrap();
    let empty = store.load().unwrap();
    assert!(
        store
            .publish(
                &empty.token,
                "home",
                None,
                &bundle,
                Metadata::default(),
                true
            )
            .is_err()
    );
    assert!(!store.root_path().join("profiles").exists());
    let receipt = store
        .publish(
            &empty.token,
            "home",
            None,
            &bundle,
            Metadata::default(),
            false,
        )
        .unwrap();
    assert!(store.load().unwrap().catalog.active.is_none());
    assert!(store.activate(&receipt.token, Some("home")).is_err());
    let bad = String::from_utf8(source.to_vec())
        .unwrap()
        .replace("127.0.0.1", "''");
    assert!(Bundle::from_memory(bad.as_bytes(), None, Default::default()).is_err());
}

#[test]
fn failed_publication_keeps_existing_catalog_exactly() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("state");
    install_golden(&root);
    let store = Store::open(&root).unwrap();
    let old = store.load().unwrap();
    let bundle = Bundle::from_memory(b"mixed-port: 9001\n", None, Default::default()).unwrap();
    let dir = zc::fsutil::SecureDir::open(&root).unwrap();
    let profiles = dir.child("profiles", false).unwrap();
    profiles
        .write_new(&storage_id("new"), b"blocked by regular file")
        .unwrap();
    assert!(
        store
            .publish(&old.token, "new", None, &bundle, Metadata::default(), false)
            .is_err()
    );
    assert_eq!(
        std::fs::read_to_string(root.join("state-v2.json")).unwrap(),
        ZIG_STATE
    );
    assert_eq!(store.load().unwrap().token, old.token);
}

#[test]
fn catalog_must_be_canonical_and_unknown_mirror_is_ignored() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("state");
    install_golden(&root);
    let store = Store::open(&root).unwrap();
    let dir = zc::fsutil::SecureDir::open(&root).unwrap();
    dir.write_new("meta.json", b"invalid mirror").unwrap();
    assert!(store.load().is_ok());
    dir.atomic_write("state-v2.json", ZIG_STATE.trim_end().as_bytes())
        .unwrap();
    assert!(store.load().is_err());
    let bad = ZIG_STATE.replace("\"generation\":0", "\"generation\":0,\"unknown\":true");
    dir.atomic_write("state-v2.json", bad.as_bytes()).unwrap();
    assert!(store.load().is_err());
}

#[test]
fn cas_child_process() {
    let Some(root) = std::env::var_os("ZC_STORE_CAS_ROOT") else {
        return;
    };
    let store = Store::open(root).unwrap();
    let old = store.load().unwrap();
    // Both children are held behind a real filesystem barrier after observing sequence 7.
    let id = std::env::var("ZC_STORE_CHILD_ID").unwrap();
    std::fs::write(store.root_path().join(format!("ready-{id}")), b"").unwrap();
    let start = std::time::Instant::now();
    while !store.root_path().join("go").exists() {
        assert!(start.elapsed() < std::time::Duration::from_secs(10));
        std::thread::sleep(std::time::Duration::from_millis(5));
    }
    let result = store.activate(&old.token, None);
    let value = match result {
        Ok(_) => "committed",
        Err(e)
            if e.downcast_ref::<zc::store::StoreError>()
                == Some(&zc::store::StoreError::Conflict) =>
        {
            "conflict"
        }
        Err(e) => panic!("unexpected error: {e}"),
    };
    std::fs::write(store.root_path().join(format!("result-{id}")), value).unwrap();
}

#[test]
fn actual_cross_process_writers_have_exactly_one_cas_winner() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("state");
    install_golden(&root);
    let spawn = |id: &str| {
        std::process::Command::new(std::env::current_exe().unwrap())
            .args(["--exact", "cas_child_process", "--nocapture"])
            .env("ZC_STORE_CAS_ROOT", &root)
            .env("ZC_STORE_CHILD_ID", id)
            .spawn()
            .unwrap()
    };
    let mut a = spawn("a");
    let mut b = spawn("b");
    let start = std::time::Instant::now();
    while !(root.join("ready-a").exists() && root.join("ready-b").exists()) {
        assert!(start.elapsed() < std::time::Duration::from_secs(10));
        std::thread::sleep(std::time::Duration::from_millis(5));
    }
    std::fs::write(root.join("go"), b"").unwrap();
    assert!(a.wait().unwrap().success());
    assert!(b.wait().unwrap().success());
    let mut results = [
        std::fs::read_to_string(root.join("result-a")).unwrap(),
        std::fs::read_to_string(root.join("result-b")).unwrap(),
    ];
    results.sort();
    assert_eq!(results, ["committed", "conflict"]);
    assert_eq!(
        Store::open(&root).unwrap().load().unwrap().catalog.sequence,
        8
    );
}

#[test]
fn source_asset_and_aggregate_limits_are_enforced_before_publish() {
    use zc::store::{Asset, FILE_LIMIT};
    let too_large = vec![b' '; FILE_LIMIT + 1];
    assert!(Bundle::from_memory(&too_large, None, Default::default()).is_err());
    let source =
        "mixed-port: 9000\nrule-providers:\n  local: {type: file, behavior: domain, path: rules}\n";
    let mut assets = std::collections::BTreeMap::new();
    assets.insert(
        "rules".into(),
        Asset {
            canonical_relative_target: "rules".into(),
            bytes: too_large,
        },
    );
    assert!(Bundle::from_memory(source.as_bytes(), None, assets).is_err());
    let mut source = String::from("mixed-port: 9000\nrule-providers:\n");
    let mut assets = std::collections::BTreeMap::new();
    for i in 0..4 {
        source.push_str(&format!(
            "  p{i}: {{type: file, behavior: domain, path: r{i}}}\n"
        ));
        assets.insert(
            format!("r{i}"),
            Asset {
                canonical_relative_target: format!("r{i}"),
                bytes: vec![b' '; FILE_LIMIT],
            },
        );
    }
    assert!(
        Bundle::from_memory(source.as_bytes(), None, assets)
            .unwrap_err()
            .to_string()
            .contains("AggregateTooLarge")
    );
}

#[test]
fn fresh_publication_respects_zig_legacy_cutover_lock() {
    use std::time::Duration;
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("state");
    let store = Store::open_with_timeout(&root, Duration::from_millis(30)).unwrap();
    let initial = store.load().unwrap();
    let dir = zc::fsutil::SecureDir::open(&root).unwrap();
    let _legacy_writer = dir
        .lock("legacy-cutover.lock", Duration::from_millis(30))
        .unwrap();
    let bundle = Bundle::from_memory(b"mixed-port: 9000\n", None, Default::default()).unwrap();
    assert!(
        store
            .publish(
                &initial.token,
                "home",
                None,
                &bundle,
                Metadata::default(),
                true
            )
            .is_err()
    );
    assert!(!root.join("state-v2.json").exists());
}

#[test]
fn remote_provider_catalog_admission_never_exposes_an_incomplete_runtime() {
    let source = "mixed-port: 9000\nrule-providers:\n  remote: {type: http, behavior: domain, path: remote.yaml, url: 'https://example.com/rules'}\n";
    let bundle = Bundle::from_memory(source.as_bytes(), None, Default::default()).unwrap();
    assert!(bundle.assets().is_empty());
    assert_eq!(bundle.remotes()[0].provider_name, "remote");
    assert!(bundle.runtime_config().is_err());
    let referenced = format!("{source}rules:\n  - RULE-SET,remote,DIRECT\n  - MATCH,DIRECT\n");
    // Counter-evidence: original legacy_catalog_bootstrap_test.zig rejects
    // referenced deferred HTTP RULE-SETs; only unused declarations are admitted.
    assert!(Bundle::from_memory(referenced.as_bytes(), None, Default::default()).is_err());
    let temp = tempfile::tempdir().unwrap();
    let store = Store::open(temp.path().join("state")).unwrap();
    let receipt = store
        .publish(
            &store.load().unwrap().token,
            "remote",
            None,
            &bundle,
            Metadata::default(),
            true,
        )
        .unwrap();
    store.activate(&receipt.token, Some("remote")).unwrap();
    for invalid in [
        referenced.replace("remote,DIRECT", "remote,missing"),
        referenced.replace("behavior: domain", "behavior: unknown"),
        referenced.replace("remote,DIRECT", "unknown,DIRECT"),
    ] {
        assert!(Bundle::from_memory(invalid.as_bytes(), None, Default::default()).is_err());
    }
}

#[test]
fn activation_does_not_bootstrap_missing_authority() {
    let temp = tempfile::tempdir().unwrap();
    let store = Store::open(temp.path().join("state")).unwrap();
    assert!(store.activate(&store.load().unwrap().token, None).is_err());
    assert!(!store.root_path().join("state-v2.json").exists());
}

#[test]
fn publishing_filters_selections_and_never_resurrects_removed_groups() {
    use zc::store::Selection;
    let temp = tempfile::tempdir().unwrap();
    let store = Store::open(temp.path().join("state")).unwrap();
    let source = b"mixed-port: 9000\nproxy-groups: [{name: Proxy, type: select, proxies: [DIRECT, REJECT]}]\nrules: ['MATCH,Proxy']\n";
    let bundle = Bundle::from_memory(source, None, Default::default()).unwrap();
    let receipt = store
        .publish(
            &store.load().unwrap().token,
            "home",
            None,
            &bundle,
            Metadata::default(),
            true,
        )
        .unwrap();
    let p = store.get("home").unwrap();
    store
        .select(
            &receipt.token,
            "home",
            &p.head,
            0,
            vec![Selection {
                group: "Proxy".into(),
                proxy: "REJECT".into(),
            }],
        )
        .unwrap();
    // Zig catalog_commands.zig filterSelections: removal -> generation 2;
    // restoring a group with no persisted selection keeps generation 2.
    for (source, sequence) in [
        (b"mixed-port: 9000\nrules: ['MATCH,DIRECT']\n".as_slice(), 3),
        (source.as_slice(), 4),
    ] {
        let before = store.load().unwrap();
        let bundle = Bundle::from_memory(source, None, Default::default()).unwrap();
        let receipt = store
            .publish(
                &before.token,
                "home",
                Some(&before.catalog.profiles[0].head),
                &bundle,
                Metadata::default(),
                true,
            )
            .unwrap();
        let after = store.load().unwrap();
        assert_eq!(after.token, receipt.token);
        assert_eq!(after.catalog.sequence, sequence);
        assert_eq!(after.catalog.profiles[0].desired.generation, 2);
        assert!(after.catalog.profiles[0].desired.selections.is_empty());
        assert_eq!(
            after.catalog.active.unwrap().revision,
            after.catalog.profiles[0].head
        );
    }
}

#[test]
fn runtime_capture_cannot_bypass_catalog_remote_admission() {
    let temp = tempfile::tempdir().unwrap();
    let source = temp.path().join("runtime.yaml");
    std::fs::write(&source, "mixed-port: 9000\nrule-providers: {remote: {type: http, behavior: domain, path: remote.yaml, url: 'https://example.com/rules'}}\nrules: ['RULE-SET,remote,DIRECT']\n").unwrap();
    let bundle = Bundle::capture_for_runtime(&source).unwrap();
    let store = Store::open(temp.path().join("state")).unwrap();
    for activate in [false, true] {
        assert!(
            store
                .publish(
                    &store.load().unwrap().token,
                    "home",
                    None,
                    &bundle,
                    Metadata::default(),
                    activate
                )
                .is_err()
        );
        assert!(!store.root_path().join("state-v2.json").exists());
        assert!(!store.root_path().join("profiles").exists());
    }
}
