use std::{fs, path::Path};
use zc::store::{Selection, Store};

const SOURCE: &[u8] = b"mixed-port: 9000\nrule-providers:\n  local: {type: file, behavior: domain, path: assets/rules.yaml}\nrules:\n  - RULE-SET,local,DIRECT\n";
const META: &[u8] = b"{\"active\":\"home\",\"configs\":{\"home\":{\"url\":\"https://example.test/sub\",\"filename\":\"Home\",\"params\":{\"target\":\"clash\"},\"selections\":{\"Proxy\":\"A\"}}}}\n";
// Generated by the actual Zig zc config list bootstrap with SOURCE/META above,
// using an isolated temporary HOME and XDG_RUNTIME_DIR (no listeners).
const ZIG_HEAD: &str = "03450c1a00f2372e3040dc0eb023cdfd";
const ZIG_DIGEST: &str = "83d45e8bb26786bc1188c673d750fdce2a2a4d610f91e1c0a9c8fc81107e5bea";

fn fixture(root: &Path) {
    fs::create_dir_all(root.join("configs/assets")).unwrap();
    fs::write(root.join("configs/home.yaml"), SOURCE).unwrap();
    fs::write(
        root.join("configs/assets/rules.yaml"),
        b"payload:\n  - example.com\n",
    )
    .unwrap();
    fs::write(root.join("meta.json"), META).unwrap();
}

#[test]
fn legacy_takeover_matches_zig_metadata_assets_identity_and_selections_once() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join(".config/zc");
    fixture(&root);
    let store = Store::open(&root).unwrap();
    let snapshot = store.load().unwrap();
    assert_eq!(snapshot.catalog.sequence, 1);
    let profile = &snapshot.catalog.profiles[0];
    assert_eq!(profile.key, "home");
    assert_eq!(profile.head, ZIG_HEAD);
    assert_eq!(profile.desired.generation, 1);
    assert_eq!(
        profile.desired.selections,
        vec![Selection {
            group: "Proxy".into(),
            proxy: "A".into()
        }]
    );
    assert_eq!(snapshot.catalog.active.unwrap().revision, ZIG_HEAD);
    let view = store.read_bundle("home", ZIG_HEAD).unwrap();
    assert_eq!(view.content_digest, ZIG_DIGEST);
    assert_eq!(
        view.metadata.url.as_deref(),
        Some("https://example.test/sub")
    );
    assert_eq!(view.metadata.filename.as_deref(), Some("Home"));
    assert_eq!(view.metadata.params[0].key, "target");
    assert_eq!(view.metadata.params[0].value, "clash");
    assert_eq!(view.bundle.source(), SOURCE);
    assert_eq!(
        view.bundle.resolve_local("assets/rules.yaml").unwrap(),
        b"payload:\n  - example.com\n"
    );
    fs::remove_dir_all(root.join("configs")).unwrap();
    fs::write(root.join("meta.json"), b"broken mirror").unwrap();
    assert_eq!(store.load().unwrap().token, snapshot.token);
    assert!(view.bundle.runtime_config().is_ok());
}

// Emitted by Zig 0.16.0 Authority.commit(compare_exchange_head) in a real
// std.testing.tmpDir, using the independently generated migration head above.
const ZIG_SCHEMA_ONE: &[u8] = b"{\"schema_version\":1,\"sequence\":1,\"profiles\":[{\"key\":\"home\",\"head\":\"03450c1a00f2372e3040dc0eb023cdfd\"}]}\n";
fn state_file(root: &Path, bytes: &[u8]) {
    zc::fsutil::SecureDir::open(root)
        .unwrap()
        .atomic_write("state-v2.json", bytes)
        .unwrap();
}

#[test]
fn schema_one_requires_exact_content_proof_before_publishing_any_revision() {
    for (authority, valid) in [
        (ZIG_SCHEMA_ONE.to_vec(), true),
        (
            b"{\"schema_version\":1,\"sequence\":1,\"profiles\":[]}\n".to_vec(),
            false,
        ),
        (
            String::from_utf8(ZIG_SCHEMA_ONE.to_vec())
                .unwrap()
                .replace(ZIG_HEAD, "00112233445566778899aabbccddeeff")
                .into_bytes(),
            false,
        ),
        (
            String::from_utf8(ZIG_SCHEMA_ONE.to_vec())
                .unwrap()
                .replace("\"sequence\":1", "\"sequence\":18446744073709551615")
                .into_bytes(),
            false,
        ),
    ] {
        let temp = tempfile::tempdir().unwrap();
        let root = temp.path().join("state");
        fixture(&root);
        let store = Store::open(&root).unwrap();
        state_file(&root, &authority);
        if valid {
            let result = store.load().unwrap();
            assert_eq!(result.catalog.sequence, 2);
            assert_eq!(result.catalog.active.unwrap().revision, ZIG_HEAD);
        } else {
            assert!(store.load().is_err());
            assert_eq!(fs::read(root.join("state-v2.json")).unwrap(), authority);
            assert!(!root.join("profiles").exists());
        }
    }
}

#[test]
fn disk_only_and_explicit_empty_selections_keep_distinct_baselines() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("state");
    fs::create_dir_all(root.join("configs")).unwrap();
    for key in ["disk", "empty", "absent"] {
        fs::write(
            root.join(format!("configs/{key}.yaml")),
            b"mixed-port: 9000\n",
        )
        .unwrap();
    }
    fs::write(
        root.join("meta.json"),
        b"{\"active\":null,\"configs\":{\"empty\":{\"selections\":{}},\"absent\":{}}}",
    )
    .unwrap();
    let store = Store::open(&root).unwrap();
    assert_eq!(store.get("empty").unwrap().desired.generation, 1);
    assert_eq!(store.get("absent").unwrap().desired.generation, 0);
    assert_eq!(store.get("disk").unwrap().desired.generation, 0);
    assert!(store.load().unwrap().catalog.active.is_none());
}

#[test]
fn every_legacy_item_is_validated_before_immutable_publication() {
    let malformed_plugin = "mixed-port: 9000\nproxies:\n  - {name: edge, type: ss, server: 127.0.0.1, port: 443, cipher: aes-128-gcm, password: secret, plugin: unsupported}\n";
    for invalid in [
        "mixed-port: [9000]\n",
        "mixed-port: 9000\nrules: [MATCH,unknown]\n",
        "mixed-port: 9000\nrule-providers:\n  absent: {type: file, behavior: domain, path: missing.yaml}\n",
        &malformed_plugin.replace("127.0.0.1", "''"),
        "mixed-port: 9000\nproxies:\n  - {name: DIRECT, type: direct}\n",
    ] {
        let temp = tempfile::tempdir().unwrap();
        let root = temp.path().join("state");
        fixture(&root);
        fs::write(root.join("configs/z.yaml"), invalid).unwrap();
        let store = Store::open(&root).unwrap();
        assert!(store.load().is_err(), "accepted {invalid}");
        assert!(!root.join("profiles").exists());
        assert!(!root.join("state-v2.json").exists());
        assert_eq!(fs::read(root.join("meta.json")).unwrap(), META);
    }
}

#[test]
fn malformed_obfs_is_preserved_but_cannot_remain_active() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("state");
    fixture(&root);
    let source = b"mixed-port: 9000\nproxies:\n  - {name: edge, type: ss, server: 127.0.0.1, port: 443, cipher: aes-128-gcm, password: secret, plugin: obfs, plugin-opts: {mode: tls, host: example.com}}\n";
    fs::write(root.join("configs/home.yaml"), source).unwrap();
    let store = Store::open(&root).unwrap();
    let snapshot = store.load().unwrap();
    assert!(snapshot.catalog.active.is_none());
    let p = &snapshot.catalog.profiles[0];
    assert_eq!(p.desired.generation, 1);
    let view = store.read_bundle(&p.key, &p.head).unwrap();
    assert_eq!(view.bundle.source(), source);
    assert!(!view.bundle.catalog_ready().unwrap());
    assert!(store.activate(&snapshot.token, Some("home")).is_err());
    assert_eq!(store.load().unwrap().token, snapshot.token);
    store.delete(&snapshot.token, "home", &p.head).unwrap();
}

#[test]
fn invalid_metadata_never_resets_or_partially_publishes_legacy_state() {
    for metadata in [
        "",
        "{}",
        "active: null\nconfigs: {}\n",
        r#"{"active":"missing","configs":{}}"#,
        r#"{"active":null,"configs":{"missing":{}}}"#,
        r#"{"active":null,"configs":{"home":{"selections":null}}}"#,
        r#"{"active":null,"configs":{"home":{"params":{"":"value"}}}}"#,
        r#"{"active":null,"configs":{"home":{},"home":{}}}"#,
        r#"{"active":null,"configs":{"home":{"unknown":true}}}"#,
        r#"{"active":null,"configs":{"home":{"selections":{"g":"A","g":"B"}}}}"#,
    ] {
        let temp = tempfile::tempdir().unwrap();
        let root = temp.path().join("state");
        fixture(&root);
        fs::write(root.join("meta.json"), metadata).unwrap();
        let store = Store::open(&root).unwrap();
        state_file(&root, ZIG_SCHEMA_ONE);
        assert!(store.load().is_err(), "accepted {metadata}");
        assert!(!root.join("profiles").exists());
        assert_eq!(
            fs::read(root.join("state-v2.json")).unwrap(),
            ZIG_SCHEMA_ONE
        );
        assert_eq!(
            fs::read(root.join("meta.json")).unwrap(),
            metadata.as_bytes()
        );
    }
}

#[test]
fn bootstrap_uses_the_opened_directory_after_root_path_rebinding() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("state");
    fixture(&root);
    let store = Store::open(&root).unwrap();
    let moved = temp.path().join("moved");
    fs::rename(&root, &moved).unwrap();
    fixture(&root);
    fs::write(
        root.join("configs/assets/rules.yaml"),
        b"payload: [wrong.example]\n",
    )
    .unwrap();
    assert_eq!(store.load().unwrap().catalog.profiles[0].head, ZIG_HEAD);
    assert!(!root.join("state-v2.json").exists());
    assert!(moved.join("state-v2.json").exists());
}

#[test]
fn zig_legacy_keys_251_through_255_remain_readable_and_deletable() {
    use zc::store::{ActiveIdentity, Bundle, Catalog, Desired, Metadata, Profile, valid_key};
    // Independent values emitted by Zig RevisionStore.publishMigration for k * n.
    let golden = [
        (
            251,
            "6f4307b242cd105a9956b8723fdaa4e78ccada5f9ed4d0672fe6f9030591c24f",
            "f183940c6b20fdcc697b61144dc726b7",
            "7efd4afccb1c2fae1effaf9439af958c3788beddbbb55acfaac42b604bc3b2d1",
        ),
        (
            252,
            "65c46bdae46ef6584a97e7b958c2fb53d8587ee475862ac57c1ba0db8c5222d3",
            "23b7a0fac5f66ce9f7fb30dce93c57d4",
            "9da42c1b35aaa13747e568f1a54424e80dea940d70dacb3e8d094bab915daa29",
        ),
        (
            253,
            "edf901d853f82f86694cdb2ef87405e24ea038f8d28ef0168c70e913bf3cf955",
            "d0e18dd62ed3843c8d2f962642fa1319",
            "7ecad42125ff104093b3ee1177a8007602655c09f6049395bd658fb5d5caec1a",
        ),
        (
            254,
            "d51e11ba0da000ff61071373e886b9e94e356373daf35058f21de9c0fd7a9ce8",
            "c824f3d1f1b272a65898fd0a29615a49",
            "6684b6bd8d9771e7c20b494494c3c92ab71f7410b46b424f1c167a550d252384",
        ),
        (
            255,
            "58598fd118f7c264277c19e1ac4766873771160989d5f7b2a99b06e6bde028e2",
            "f5b9dcc37374449d8b5f04d8748a4eab",
            "f9d49f52e318d2136545acea43a6c3dfe819e28c124f43f7c42b1108e5ecf279",
        ),
    ];
    for (length, id, head, content_digest) in golden {
        let temp = tempfile::tempdir().unwrap();
        let root = temp.path().join("state");
        let store = Store::open(&root).unwrap();
        let key = "k".repeat(length);
        assert!(!valid_key(&key));
        assert!(valid_key(&"k".repeat(250)));
        let bundle = Bundle::from_memory(b"mixed-port: 9000\n", None, Default::default()).unwrap();
        assert!(
            store
                .publish(
                    &store.load().unwrap().token,
                    &key,
                    None,
                    &bundle,
                    Metadata::default(),
                    false
                )
                .is_err()
        );
        assert!(!root.join("profiles").exists());
        let dir = zc::fsutil::SecureDir::open(&root).unwrap();
        let profile = dir
            .child("profiles", true)
            .unwrap()
            .child(id, true)
            .unwrap();
        profile
            .write_new(
                "identity.json",
                serde_json::to_string(
                    &serde_json::json!({"schema_version":1,"key":key,"storage_id":id}),
                )
                .unwrap()
                .as_bytes(),
            )
            .unwrap();
        let revision = profile
            .child("revisions", true)
            .unwrap()
            .child(head, true)
            .unwrap();
        revision.child("objects", true).unwrap();
        revision
            .write_new("source.yaml", b"mixed-port: 9000\n")
            .unwrap();
        revision.write_new("manifest.json", serde_json::to_string(&serde_json::json!({
            "schema_version":1,"key":key,"storage_id":id,"revision":head,"content_digest":content_digest,
            "metadata":{"url":null,"filename":null,"params":[]},"override":null,
            "source":{"size":17,"sha256":"1a0d9cbe3966156e2d2c94a3e7211e147097950cc2fa46fc496254348f9882ff"},
            "materialized_source":null,"aggregate_bytes":17,"local_assets":[],"remote_providers":[]
        })).unwrap().as_bytes()).unwrap();
        let catalog = Catalog {
            schema_version: 2,
            sequence: 7,
            active: Some(ActiveIdentity {
                key: key.clone(),
                revision: head.into(),
            }),
            profiles: vec![Profile {
                key: key.clone(),
                storage_id: id.into(),
                head: head.into(),
                desired: Desired::default(),
            }],
        };
        state_file(
            &root,
            format!("{}\n", serde_json::to_string(&catalog).unwrap()).as_bytes(),
        );
        dir.write_new("meta.json", b"broken legacy mirror").unwrap();
        assert_eq!(store.get(&key).unwrap().head, head);
        assert_eq!(
            store.read_bundle(&key, head).unwrap().content_digest,
            content_digest
        );
        store
            .delete(&store.load().unwrap().token, &key, head)
            .unwrap();
        assert!(store.list().unwrap().is_empty());
        assert!(store.load().unwrap().catalog.active.is_none());
    }
}

#[tokio::test]
async fn persisted_override_executes_once_before_capturing_replaced_assets() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("state");
    fixture(&root);
    let source = b"mixed-port: 9000\nrule-providers:\n  missing: {type: file, behavior: domain, path: absent.yaml}\nrules: [\"RULE-SET,missing,DIRECT\"]\n";
    fs::write(root.join("configs/home.yaml"), source).unwrap();
    let counter = temp.path().join("counter");
    let script = temp.path().join("override.sh");
    fs::write(&script, format!("#!/bin/sh\nprintf 'executed\\n' >> '{}'\n[ \"$ZC_OVERRIDE_COMMAND\" = legacy-migration ] || exit 1\n[ \"$ZC_OVERRIDE_ARG_COUNT\" = 0 ] || exit 2\n[ -z \"$ZC_OVERRIDE_ARG_PORT\" ] || exit 3\nprintf 'mixed-port: 9001\\nrule-providers: {{}}\\nrules: [\"MATCH,DIRECT\"]\\n'\n", counter.display())).unwrap();
    fs::write(root.join("meta.json"), serde_json::to_vec(&serde_json::json!({"active":"home","configs":{"home":{"override_script":script,"params":{"port":"9999"}}}})).unwrap()).unwrap();
    let store = Store::open(&root).unwrap();
    let snapshot = store.load().unwrap();
    let p = &snapshot.catalog.profiles[0];
    let view = store.read_bundle(&p.key, &p.head).unwrap();
    assert_eq!(view.bundle.source(), source);
    assert_eq!(
        view.bundle.runtime_config().unwrap().document()["mixed-port"],
        9001
    );
    let frozen = view.frozen_override.unwrap();
    assert_eq!(frozen.command, "legacy-migration");
    assert!(frozen.args.is_empty());
    assert_eq!(view.metadata.params[0].value, "9999");
    assert_eq!(frozen.script_bytes, fs::read(&script).unwrap());
    assert_eq!(fs::read(&counter).unwrap(), b"executed\n");
    fs::remove_dir_all(root.join("configs")).unwrap();
    fs::remove_file(root.join("meta.json")).unwrap();
    fs::remove_file(script).unwrap();
    assert_eq!(store.load().unwrap().token, snapshot.token);
    assert_eq!(fs::read(&counter).unwrap(), b"executed\n");
}

#[test]
fn repeat_witness_rejects_noncooperative_source_or_metadata_edits() {
    for target in ["configs/home.yaml", "meta.json", "override.sh"] {
        let temp = tempfile::tempdir().unwrap();
        let root = temp.path().join("state");
        fixture(&root);
        fs::write(root.join("configs/z.yaml"), b"mixed-port: 9000\n").unwrap();
        let script = root.join("override.sh");
        fs::write(
            &script,
            format!(
                "#!/bin/sh\nprintf 'changed' > '{}'\nprintf 'mixed-port: 9001\\n'\n",
                root.join(target).display()
            ),
        )
        .unwrap();
        fs::write(root.join("meta.json"), serde_json::to_vec(&serde_json::json!({"active":null,"configs":{"home":{},"z":{"override_script":script}}})).unwrap()).unwrap();
        let store = Store::open(&root).unwrap();
        assert!(store.load().is_err(), "accepted changed {target}");
        assert!(!root.join("profiles").exists());
        assert!(!root.join("state-v2.json").exists());
    }
}

#[test]
fn escaping_assets_symlink_metadata_and_special_files_fail_without_blocking() {
    use std::os::unix::fs::symlink;
    for target in [
        "meta.json",
        "configs/home.yaml",
        "configs/assets/rules.yaml",
        "configs",
    ] {
        for special in [false, true] {
            let temp = tempfile::tempdir().unwrap();
            let root = temp.path().join("state");
            fixture(&root);
            let path = root.join(target);
            if path.is_dir() {
                fs::remove_dir_all(&path).unwrap();
            } else {
                fs::remove_file(&path).unwrap();
            }
            if special {
                assert!(
                    std::process::Command::new("mkfifo")
                        .arg(&path)
                        .status()
                        .unwrap()
                        .success()
                );
            } else {
                let outside = temp.path().join("outside");
                fs::write(&outside, SOURCE).unwrap();
                symlink(&outside, &path).unwrap();
            }
            let store = Store::open(&root).unwrap();
            assert!(store.load().is_err());
            assert!(!root.join("profiles").exists());
            assert!(!root.join("state-v2.json").exists());
        }
    }
}

#[test]
fn takeover_freezes_cooperative_writers_and_does_not_overwrite_new_legacy_state() {
    use std::time::Duration;
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("state");
    let store = Store::open_with_timeout(&root, Duration::from_millis(30)).unwrap();
    let missing = store.load().unwrap();
    fixture(&root);
    let dir = zc::fsutil::SecureDir::open(&root).unwrap();
    let guard = dir
        .lock("legacy-cutover.lock", Duration::from_millis(30))
        .unwrap();
    assert!(store.load().is_err());
    assert!(!root.join("profiles").exists());
    drop(guard);
    let bundle =
        zc::store::Bundle::from_memory(b"mixed-port: 9000\n", None, Default::default()).unwrap();
    assert!(
        store
            .publish(
                &missing.token,
                "other",
                None,
                &bundle,
                Default::default(),
                true
            )
            .is_err()
    );
    assert!(!root.join("state-v2.json").exists());
    assert_eq!(store.load().unwrap().catalog.profiles[0].head, ZIG_HEAD);
}

#[test]
fn takeover_child() {
    let Some(root) = std::env::var_os("ZC_LEGACY_TEST_ROOT") else {
        return;
    };
    let store = Store::open(root).unwrap();
    let snapshot = store.load().unwrap();
    assert_eq!(snapshot.catalog.sequence, 1);
    assert_eq!(snapshot.catalog.profiles[0].head, ZIG_HEAD);
}

#[test]
fn concurrent_process_takeovers_commit_once() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("state");
    fixture(&root);
    let spawn = || {
        std::process::Command::new(std::env::current_exe().unwrap())
            .args(["--exact", "takeover_child", "--nocapture"])
            .env("ZC_LEGACY_TEST_ROOT", &root)
            .env("HOME", temp.path())
            .spawn()
            .unwrap()
    };
    let mut a = spawn();
    let mut b = spawn();
    assert!(a.wait().unwrap().success());
    assert!(b.wait().unwrap().success());
    let store = Store::open(&root).unwrap();
    assert_eq!(store.load().unwrap().catalog.sequence, 1);
}

#[tokio::test]
async fn deferred_http_is_rejected_offline_but_unmanaged_runtime_fetch_remains_supported() {
    use tokio::io::{AsyncReadExt, AsyncWriteExt};
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("state");
    fixture(&root);
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let address = listener.local_addr().unwrap();
    let source = format!(
        "mixed-port: 9000\nrule-providers:\n  remote: {{type: http, behavior: domain, path: remote.yaml, url: 'http://{address}/rules'}}\nrules: ['RULE-SET,remote,REJECT','MATCH,DIRECT']\n"
    );
    fs::write(root.join("configs/home.yaml"), &source).unwrap();
    let store = Store::open(&root).unwrap();
    // Original legacy_catalog_bootstrap_test.zig:381 rejects this before writes.
    assert!(store.load().is_err());
    assert!(!root.join("state-v2.json").exists());
    assert!(!root.join("profiles").exists());
    let server = tokio::spawn(async move {
        let (mut socket, _) = listener.accept().await.unwrap();
        let mut request = [0; 4096];
        assert!(socket.read(&mut request).await.unwrap() > 0);
        let body = "payload: [blocked.example]\n";
        socket
            .write_all(
                format!(
                    "HTTP/1.1 200 OK\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{body}",
                    body.len()
                )
                .as_bytes(),
            )
            .await
            .unwrap();
    });
    let unmanaged = zc::store::Bundle::capture_for_runtime(root.join("configs/home.yaml")).unwrap();
    assert!(unmanaged.catalog_ready().is_err());
    assert!(unmanaged.runtime_config().is_err());
    let fetched = zc::config::fetch_http_assets(&source).await.unwrap();
    let config = unmanaged.runtime_config_with_assets(&fetched).unwrap();
    assert_eq!(config.rules_json()["rules"].as_array().unwrap().len(), 2);
    assert_eq!(
        config.rules_json()["rules"][0]["payload"],
        "blocked.example"
    );
    server.await.unwrap();
    assert!(store.load().is_err());
}

#[test]
fn invalid_late_orphan_identity_is_rejected_before_publishing_earlier_items() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("state");
    fixture(&root);
    fs::write(root.join("configs/z.yaml"), b"mixed-port: 9000\n").unwrap();
    let store = Store::open(&root).unwrap();
    let profiles = zc::fsutil::SecureDir::open(&root)
        .unwrap()
        .child("profiles", true)
        .unwrap();
    profiles
        .write_new(&zc::store::storage_id("z"), b"not a profile directory")
        .unwrap();
    assert!(store.load().is_err());
    assert!(
        !root
            .join(format!("profiles/{}", zc::store::storage_id("home")))
            .exists()
    );
    assert!(!root.join("state-v2.json").exists());
}

#[test]
fn invalid_materialized_plugin_is_not_raw_recovery_data() {
    use std::os::unix::fs::PermissionsExt;
    for patch in [
        "proxies: [{name: edge, type: ss, server: example.com, port: 8388, cipher: aes-128-gcm, password: secret, plugin: obfs, plugin-opts: {mode: tls, host: example.com}}]\nrules: ['MATCH,edge']\n",
        "",
    ] {
        let temp = tempfile::tempdir().unwrap();
        let root = temp.path().join("state");
        fs::create_dir_all(root.join("configs")).unwrap();
        let source = if patch.is_empty() {
            "mixed-port: 9000\nproxies: [{name: edge, type: ss, server: example.com, port: 8388, cipher: aes-128-gcm, password: secret, plugin: obfs, plugin-opts: {mode: tls, host: example.com}}]\nrules: ['MATCH,edge']\n"
        } else {
            "mixed-port: 9000\n"
        };
        fs::write(root.join("configs/home.yaml"), source).unwrap();
        let script = temp.path().join("override.sh");
        fs::write(&script, format!("#!/bin/sh\ncat <<'PATCH'\n{patch}PATCH\n")).unwrap();
        fs::set_permissions(&script, fs::Permissions::from_mode(0o700)).unwrap();
        fs::write(
            root.join("meta.json"),
            serde_json::to_vec(
                &serde_json::json!({"active":"home","configs":{"home":{"override_script":script}}}),
            )
            .unwrap(),
        )
        .unwrap();
        assert!(Store::open(&root).unwrap().load().is_err());
        assert!(!root.join("state-v2.json").exists());
        assert!(!root.join("profiles").exists());
    }
}

#[test]
fn actual_zig_override_head_and_same_path_schema_one_proof_are_preserved() {
    use std::os::unix::fs::PermissionsExt;
    use zc::store::{Bundle, FrozenOverride, Metadata};
    let temp = tempfile::tempdir().unwrap();
    let source = include_bytes!("fixtures/state_minimal_source.yaml");
    let effective = include_bytes!("fixtures/state_minimal_effective.yaml");
    let script_bytes = include_bytes!("fixtures/state_override.sh");
    let frozen = |path: String| FrozenOverride {
        script_name: "override.sh".into(),
        script_bytes: script_bytes.to_vec(),
        command: "legacy-migration".into(),
        config_path: Some(path),
        timeout_ms: 5000,
        args: vec![],
        patch_bytes: include_bytes!("fixtures/state_patch.yaml").to_vec(),
    };
    let bundle = Bundle::from_memory(source, Some(effective), Default::default()).unwrap();
    let oracle: serde_json::Value =
        serde_json::from_slice(include_bytes!("fixtures/state_minimal_manifest.json")).unwrap();
    let evidence = Store::open(temp.path().join("evidence")).unwrap();
    evidence
        .publish_frozen(
            &evidence.load().unwrap().token,
            "home",
            None,
            &bundle,
            Metadata::default(),
            Some(frozen(
                oracle["override"]["config_path"].as_str().unwrap().into(),
            )),
            true,
        )
        .unwrap();
    let p = evidence.get("home").unwrap();
    assert_eq!(p.head, "5109ae8cab8fed6a1f8b277cfd767d37");
    assert_eq!(
        evidence
            .read_bundle("home", &p.head)
            .unwrap()
            .content_digest,
        "49bd9dc5364a2ea3c235d6ac8ab3f4e4b32ad888885b5c7ce778a1ea8ac8bffa"
    );

    let root = temp.path().join("legacy");
    fs::create_dir_all(root.join("configs")).unwrap();
    fs::write(root.join("configs/home.yaml"), source).unwrap();
    let script = temp.path().join("override.sh");
    fs::write(&script, script_bytes).unwrap();
    fs::set_permissions(&script, fs::Permissions::from_mode(0o700)).unwrap();
    let meta = serde_json::to_vec(
        &serde_json::json!({"active":"home","configs":{"home":{"override_script":script}}}),
    )
    .unwrap();
    fs::write(root.join("meta.json"), &meta).unwrap();
    // Golden materialized bytes, not the implementation's materializer, seed
    // the proof at this machine's exact canonical invocation path.
    let expected_store = Store::open(temp.path().join("expected")).unwrap();
    expected_store
        .publish_frozen(
            &expected_store.load().unwrap().token,
            "home",
            None,
            &bundle,
            Metadata::default(),
            Some(frozen(
                root.join("configs/home.yaml")
                    .canonicalize()
                    .unwrap()
                    .to_str()
                    .unwrap()
                    .into(),
            )),
            true,
        )
        .unwrap();
    let head = expected_store.get("home").unwrap().head;
    let schema1 = serde_json::to_vec(&serde_json::json!({"schema_version":1,"sequence":7,"profiles":[{"key":"home","head":head}]})).unwrap();
    let store = Store::open(&root).unwrap();
    for _ in 0..2 {
        state_file(&root, &schema1);
        let snapshot = store.load().unwrap();
        assert_eq!(snapshot.catalog.sequence, 8);
        assert_eq!(snapshot.catalog.profiles[0].head, head);
        let view = store.read_bundle("home", &head).unwrap();
        assert_eq!(view.bundle.materialized().unwrap(), effective);
        assert!(view.bundle.runtime_config().is_ok());
    }
    state_file(&root, &schema1);
    fs::write(&script, b"#!/bin/sh\nprintf 'mixed-port: 9002\\n'\n").unwrap();
    assert!(
        store
            .load()
            .unwrap_err()
            .to_string()
            .contains("LegacyProofMismatch")
    );
    assert_eq!(fs::read(root.join("state-v2.json")).unwrap(), schema1);
}
