const std = @import("std");
const builtin = @import("builtin");

// This test-only executable intentionally imports no production module. Its
// crypto, address codec, SOCKS framing, deadlines, and socket I/O are separate
// implementations so E2E checks cannot agree with production by construction.
const wire_size_max: usize = 65_507;
const receive_size_max: usize = 65_536;
const packet_count_max: u32 = 4_096;
const service_lifetime_ms: i64 = 180_000;
const probe_lifetime_ms: i64 = 5_000;
const absence_window_ms: i64 = 350;
const teardown_window_ms: i64 = 1_000;
const tag_size: usize = 16;
const nonce_size: usize = 12;
const address_size_max: usize = 259;
const domain_size_max: usize = 255;
const association_count_max: usize = 64;
const syscall_retry_max: usize = 4_096;
const stream_io_iteration_max: usize = 65_536;
const password_size_max: usize = 1_024;
const nonce_argument_size_max: usize = 1_024;
const tagged_payload_size_max: usize = nonce_argument_size_max + 16;
const ipv6_v6only_option: u32 = switch (builtin.os.tag) {
    .macos => 27,
    .linux => 26,
    else => @compileError("Shadowsocks UDP E2E supports Darwin and Linux"),
};

comptime {
    std.debug.assert(wire_size_max == std.math.maxInt(u16) - 20 - 8);
    std.debug.assert(receive_size_max > wire_size_max);
    std.debug.assert(packet_count_max == 4_096);
    std.debug.assert(service_lifetime_ms == 180 * 1_000);
    std.debug.assert(tag_size == 16);
    std.debug.assert(nonce_size == 12);
    std.debug.assert(address_size_max == 1 + 1 + domain_size_max + 2);
    std.debug.assert(tagged_payload_size_max == nonce_argument_size_max + 16);
    std.debug.assert(association_count_max == 64);
}

const ServeMode = enum {
    normal,
    bad_tag_once,
    truncated_salt_once,
    truncated_tag_once,
};

const ResponseKind = enum {
    normal,
    bad_tag,
    truncated_salt,
    truncated_tag,

    fn marker(self: ResponseKind) []const u8 {
        return switch (self) {
            .normal => "NORMAL",
            .bad_tag => "BAD_TAG",
            .truncated_salt => "TRUNCATED_SALT",
            .truncated_tag => "TRUNCATED_TAG",
        };
    }
};

const EchoFamily = enum {
    ipv4,
    ipv6,
};

const InvalidKind = enum {
    rsv1,
    rsv2,
    frag,
    atyp,
    truncated,
};

const ProbeKind = enum {
    roundtrip,
    roundtrip_domain,
    roundtrip_ipv6,
    response_drop_recovery,
    invalid_then_valid,
    source_pin,
    client_ip,
    control_close,
    selection_teardown,
    associate_rejected,
    max,
    capacity,
};

pub fn main(init: std.process.Init) !void {
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    if (args.len < 2) return error.InvalidArguments;

    if (std.mem.eql(u8, args[1], "serve")) {
        try mainServe(init.io, args);
        return;
    }
    if (std.mem.eql(u8, args[1], "echo")) {
        try mainEcho(init.io, args);
        return;
    }
    if (std.mem.eql(u8, args[1], "probe")) {
        const probe_name = try mainProbe(init.io, args);
        try printLine(
            init.io,
            "E2E_SS_UDP_PROBE_PASS={s}\n",
            .{probe_name},
        );
        return;
    }
    return error.InvalidArguments;
}

fn decodeLiteralHex(comptime hex: []const u8) ![hex.len / 2]u8 {
    var bytes: [hex.len / 2]u8 = undefined;
    _ = try std.fmt.hexToBytes(&bytes, hex);
    return bytes;
}

fn expectLiteralDatagramVector(
    comptime cipher: Cipher,
    comptime plaintext_hex: []const u8,
    comptime salt_hex: []const u8,
    comptime wire_hex: []const u8,
) !void {
    // These disjoint vectors are generated by the independent Node built-in
    // crypto procedure in scripts/e2e/generate-shadowsocks-udp-vectors.mjs.
    const plaintext = try decodeLiteralHex(plaintext_hex);
    const salt = try decodeLiteralHex(salt_hex);
    const expected_wire = try decodeLiteralHex(wire_hex);
    var crypto = DatagramCrypto.init(cipher, "oracle-vector-password-v1");
    defer crypto.deinit();

    var wire_buffer: [expected_wire.len]u8 = undefined;
    const wire = try crypto.sealWithSalt(&plaintext, &salt, &wire_buffer);
    try std.testing.expectEqualSlices(u8, &expected_wire, wire);

    var plaintext_buffer: [plaintext.len]u8 = undefined;
    const opened = try crypto.open(&expected_wire, &plaintext_buffer);
    try std.testing.expectEqualSlices(u8, &plaintext, opened);
}

test "Shadowsocks UDP oracle EVP BytesToKey matches the independent vector" {
    const key = deriveMasterKey("oracle-vector-password-v1", 32);
    const expected = try decodeLiteralHex(
        "07e6735dc91027c7bbc6756fbe4725909299d201b11672d42922f3833b247434",
    );
    try std.testing.expectEqualSlices(u8, &expected, &key);
}

test "Shadowsocks UDP oracle AES-128-GCM opens and seals the independent literal wire" {
    try expectLiteralDatagramVector(
        .aes_128_gcm,
        "01c000027b14e96165733132382d6e6f64652d766563746f72",
        "f0e0d0c0b0a090807060504030201000",
        "f0e0d0c0b0a090807060504030201000" ++
            "fcdb69b1dd02167b6b5fb4e6aa16d75c8656108cc2879ee2a02bee68cf79ad110458a788b1b9f090df",
    );
}

test "Shadowsocks UDP oracle AES-256-GCM opens and seals the independent literal wire" {
    try expectLiteralDatagramVector(
        .aes_256_gcm,
        "030e766563746f722e6578616d706c6501bb6165733235362d6e6f64652d766563746f72",
        "00112233445566778899aabbccddeeff" ++
            "ffeeddccbbaa99887766554433221100",
        "00112233445566778899aabbccddeeff" ++
            "ffeeddccbbaa99887766554433221100" ++
            "38533e59c4553684cafa3f1d7b6d02018d77145fe699c2afa1bebdc1cbbbb294656bb938cae74ac48fc9929da1916802ad319230",
    );
}

test "Shadowsocks UDP oracle ChaCha20-IETF opens and seals the independent literal wire" {
    try expectLiteralDatagramVector(
        .chacha20_ietf_poly1305,
        "0420010db800000000000000000000004200356368616368612d6e6f64652d766563746f72",
        "102132435465768798a9bacbdcedfe0f" ++
            "001326394c5f728598abbed1e4f70a1b",
        "102132435465768798a9bacbdcedfe0f" ++
            "001326394c5f728598abbed1e4f70a1b" ++
            "b6af4cc3f4ecabccb6c146b7d7c2bd6d2525daaeb49f40ac9e34ab05fa3b919157ceaddc00a5be9b9bed19cf864c77d064d2495311",
    );
}

test "Shadowsocks UDP oracle rejects bad tags and preserves packet recovery" {
    const literal = try decodeLiteralHex(
        "000102030405060708090a0b0c0d0e0f" ++
            "5f258e0c61142e2adf12b78447f4379ccad5b5fe1ca235e4cdd27f71ed4e3d816cc95508",
    );
    var crypto = DatagramCrypto.init(.aes_128_gcm, "password");
    defer crypto.deinit();
    var corrupted = literal;
    corrupted[corrupted.len - 1] ^= 0x01;
    var plaintext: [64]u8 = undefined;
    try std.testing.expectError(
        error.AuthenticationFailed,
        crypto.open(&corrupted, &plaintext),
    );
    const opened = try crypto.open(&literal, &plaintext);
    try std.testing.expectEqualSlices(
        u8,
        &(try decodeLiteralHex("030b6578616d706c652e636f6d003568656c6c6f")),
        opened,
    );
}

test "Shadowsocks UDP oracle enforces every cipher full wire and output boundary" {
    const ciphers = [_]Cipher{
        .aes_128_gcm,
        .aes_256_gcm,
        .chacha20_ietf_poly1305,
    };
    var plaintext: [wire_size_max + 1]u8 = @splat(0x5a);
    var output: [wire_size_max]u8 = undefined;
    var oversized: [wire_size_max + 1]u8 = @splat(0);
    const salt_storage = [_]u8{0x11} ** 32;

    for (ciphers) |cipher| {
        var crypto = DatagramCrypto.init(cipher, "password");
        defer crypto.deinit();
        const plaintext_len_max = wire_size_max - cipher.saltLen() - tag_size;
        const salt = salt_storage[0..cipher.saltLen()];
        const exact = try crypto.sealWithSalt(
            plaintext[0..plaintext_len_max],
            salt,
            &output,
        );
        try std.testing.expectEqual(@as(usize, wire_size_max), exact.len);
        try std.testing.expectError(
            error.DatagramTooLarge,
            crypto.sealWithSalt(
                plaintext[0 .. plaintext_len_max + 1],
                salt,
                &output,
            ),
        );
        try std.testing.expectError(
            error.OutputTooSmall,
            crypto.open(exact, plaintext[0 .. plaintext_len_max - 1]),
        );
        try std.testing.expectError(
            error.DatagramTooLarge,
            crypto.open(&oversized, &plaintext),
        );
    }
}

test "Shadowsocks UDP oracle parses address-prefixed plaintext independently" {
    const ipv4 = try parseAddressPayload("\x01\x7f\x00\x00\x01\x14\xe9ping");
    try std.testing.expectEqual(AddressKind.ipv4, ipv4.address.kind);
    try std.testing.expectEqual(@as(u16, 5353), ipv4.address.port);
    try std.testing.expectEqualSlices(u8, &.{ 127, 0, 0, 1 }, ipv4.address.host);
    try std.testing.expectEqualStrings("ping", ipv4.payload);

    const domain = try parseAddressPayload("\x03\x03dns\x00\x35query");
    try std.testing.expectEqual(AddressKind.domain, domain.address.kind);
    try std.testing.expectEqualStrings("dns", domain.address.host);
    try std.testing.expectEqualStrings("query", domain.payload);

    const ipv6 = try parseAddressPayload(
        "\x04\x00\x01\x02\x03\x04\x05\x06\x07" ++
            "\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f\x01\xbbdata",
    );
    try std.testing.expectEqual(AddressKind.ipv6, ipv6.address.kind);
    try std.testing.expectEqual(@as(usize, 16), ipv6.address.host.len);
    try std.testing.expectEqualStrings("data", ipv6.payload);

    try std.testing.expectError(error.InvalidAddressType, parseAddressPayload("\x02x"));
    try std.testing.expectError(error.TruncatedAddress, parseAddressPayload("\x03\x05ab"));
}

test "Shadowsocks UDP oracle builds and parses strict SOCKS UDP framing" {
    var wire: [64]u8 = undefined;
    const encoded = try buildSocksUdpIpv4(
        &wire,
        .{ .ip = .{ 127, 0, 0, 1 }, .port = 5353 },
        "nonce",
    );
    try std.testing.expectEqualSlices(
        u8,
        "\x00\x00\x00\x01\x7f\x00\x00\x01\x14\xe9nonce",
        encoded,
    );
    const parsed = try parseSocksUdp(encoded);
    try std.testing.expectEqual(AddressKind.ipv4, parsed.address.kind);
    try std.testing.expectEqual(@as(u16, 5353), parsed.address.port);
    try std.testing.expectEqualStrings("nonce", parsed.payload);

    var invalid: [15]u8 = undefined;
    @memcpy(&invalid, encoded);
    invalid[0] = 1;
    try std.testing.expectError(error.ReservedNotZero, parseSocksUdp(&invalid));
    @memcpy(&invalid, encoded);
    invalid[2] = 1;
    try std.testing.expectError(error.FragmentationNotSupported, parseSocksUdp(&invalid));

    var ipv6_wire: [64]u8 = undefined;
    const ipv6 = try buildSocksUdpIpv6(
        &ipv6_wire,
        .{
            .ip = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 },
            .port = 53,
        },
        "v6",
    );
    const parsed_ipv6 = try parseSocksUdp(ipv6);
    try std.testing.expectEqual(AddressKind.ipv6, parsed_ipv6.address.kind);
    try std.testing.expectEqual(@as(u16, 53), parsed_ipv6.address.port);
    try std.testing.expectEqualStrings("v6", parsed_ipv6.payload);

    var domain_wire: [64]u8 = undefined;
    const domain = try buildSocksUdpDomain(
        &domain_wire,
        "localhost",
        5353,
        "domain",
    );
    const parsed_domain = try parseSocksUdp(domain);
    try std.testing.expectEqual(AddressKind.domain, parsed_domain.address.kind);
    try std.testing.expectEqualStrings("localhost", parsed_domain.address.host);
    try std.testing.expectEqualStrings("domain", parsed_domain.payload);
}

test "Shadowsocks UDP oracle parses only successful IPv4 associate replies" {
    const reply = [_]u8{ 5, 0, 0, 1, 127, 0, 0, 1, 0x23, 0x45 };
    const endpoint = try parseAssociateReply(&reply);
    try std.testing.expectEqual(Endpoint4{
        .ip = .{ 127, 0, 0, 1 },
        .port = 0x2345,
    }, endpoint);

    var failure = reply;
    failure[1] = 1;
    try std.testing.expectError(error.AssociateRejected, parseAssociateReply(&failure));
    var domain = reply;
    domain[3] = 3;
    try std.testing.expectError(error.NonIpv4AssociateReply, parseAssociateReply(&domain));
}

const Cipher = enum {
    aes_128_gcm,
    aes_256_gcm,
    chacha20_ietf_poly1305,

    fn parse(text: []const u8) ?Cipher {
        if (std.mem.eql(u8, text, "aes-128-gcm")) return .aes_128_gcm;
        if (std.mem.eql(u8, text, "aes-256-gcm")) return .aes_256_gcm;
        if (std.mem.eql(u8, text, "chacha20-ietf-poly1305")) {
            return .chacha20_ietf_poly1305;
        }
        return null;
    }

    fn keyLen(self: Cipher) usize {
        return switch (self) {
            .aes_128_gcm => 16,
            .aes_256_gcm, .chacha20_ietf_poly1305 => 32,
        };
    }

    fn saltLen(self: Cipher) usize {
        return self.keyLen();
    }
};

const DatagramCrypto = struct {
    cipher: Cipher,
    master_key: [32]u8,

    fn init(cipher: Cipher, password: []const u8) DatagramCrypto {
        return .{
            .cipher = cipher,
            .master_key = deriveMasterKey(password, cipher.keyLen()),
        };
    }

    fn deinit(self: *DatagramCrypto) void {
        std.crypto.secureZero(u8, &self.master_key);
        self.* = undefined;
    }

    fn sealRandom(
        self: *const DatagramCrypto,
        io: std.Io,
        plaintext: []const u8,
        output: []u8,
    ) ![]u8 {
        var salt_storage: [32]u8 = undefined;
        defer std.crypto.secureZero(u8, &salt_storage);
        const salt = salt_storage[0..self.cipher.saltLen()];
        try std.Io.randomSecure(io, salt);
        return self.sealWithSalt(plaintext, salt, output);
    }

    fn sealWithSalt(
        self: *const DatagramCrypto,
        plaintext: []const u8,
        salt: []const u8,
        output: []u8,
    ) ![]u8 {
        const salt_len = self.cipher.saltLen();
        if (salt.len != salt_len) return error.InvalidSalt;
        const plaintext_end = std.math.add(
            usize,
            salt_len,
            plaintext.len,
        ) catch return error.DatagramTooLarge;
        const wire_len = std.math.add(
            usize,
            plaintext_end,
            tag_size,
        ) catch return error.DatagramTooLarge;
        if (wire_len > wire_size_max) return error.DatagramTooLarge;
        if (output.len < wire_len) return error.OutputTooSmall;

        @memcpy(output[0..salt_len], salt);
        @memcpy(output[salt_len..plaintext_end], plaintext);
        var subkey = [_]u8{0} ** 32;
        defer std.crypto.secureZero(u8, &subkey);
        self.deriveSubkey(salt, &subkey);
        const ciphertext = output[salt_len..plaintext_end];
        const tag: *[tag_size]u8 = output[plaintext_end..wire_len][0..tag_size];
        encrypt(self.cipher, ciphertext, tag, &subkey);
        return output[0..wire_len];
    }

    fn open(
        self: *const DatagramCrypto,
        wire: []const u8,
        output: []u8,
    ) ![]u8 {
        if (wire.len > wire_size_max) return error.DatagramTooLarge;
        const salt_len = self.cipher.saltLen();
        const overhead = std.math.add(
            usize,
            salt_len,
            tag_size,
        ) catch return error.InvalidPacket;
        if (wire.len < overhead) return error.InvalidPacket;
        const ciphertext_end = wire.len - tag_size;
        const plaintext_len = ciphertext_end - salt_len;
        if (output.len < plaintext_len) return error.OutputTooSmall;

        var tag: [tag_size]u8 = undefined;
        @memcpy(&tag, wire[ciphertext_end..]);
        @memcpy(output[0..plaintext_len], wire[salt_len..ciphertext_end]);
        var subkey = [_]u8{0} ** 32;
        defer std.crypto.secureZero(u8, &subkey);
        self.deriveSubkey(wire[0..salt_len], &subkey);
        try decrypt(
            self.cipher,
            output[0..plaintext_len],
            tag,
            &subkey,
        );
        return output[0..plaintext_len];
    }

    fn deriveSubkey(
        self: *const DatagramCrypto,
        salt: []const u8,
        subkey: *[32]u8,
    ) void {
        const HmacSha1 = std.crypto.auth.hmac.HmacSha1;
        const HkdfSha1 = std.crypto.kdf.hkdf.Hkdf(HmacSha1);
        const key_len = self.cipher.keyLen();
        var prk = HkdfSha1.extract(salt, self.master_key[0..key_len]);
        defer std.crypto.secureZero(u8, &prk);
        subkey.* = @splat(0);
        HkdfSha1.expand(subkey[0..key_len], "ss-subkey", prk);
    }

    fn encrypt(
        cipher: Cipher,
        text: []u8,
        tag: *[tag_size]u8,
        subkey: *const [32]u8,
    ) void {
        const nonce = [_]u8{0} ** nonce_size;
        switch (cipher) {
            .aes_128_gcm => std.crypto.aead.aes_gcm.Aes128Gcm.encrypt(
                text,
                tag,
                text,
                "",
                nonce,
                subkey[0..16].*,
            ),
            .aes_256_gcm => std.crypto.aead.aes_gcm.Aes256Gcm.encrypt(
                text,
                tag,
                text,
                "",
                nonce,
                subkey.*,
            ),
            .chacha20_ietf_poly1305 => {
                std.crypto.aead.chacha_poly.ChaCha20Poly1305.encrypt(
                    text,
                    tag,
                    text,
                    "",
                    nonce,
                    subkey.*,
                );
            },
        }
    }

    fn decrypt(
        cipher: Cipher,
        text: []u8,
        tag: [tag_size]u8,
        subkey: *const [32]u8,
    ) !void {
        const nonce = [_]u8{0} ** nonce_size;
        switch (cipher) {
            .aes_128_gcm => std.crypto.aead.aes_gcm.Aes128Gcm.decrypt(
                text,
                text,
                tag,
                "",
                nonce,
                subkey[0..16].*,
            ) catch return error.AuthenticationFailed,
            .aes_256_gcm => std.crypto.aead.aes_gcm.Aes256Gcm.decrypt(
                text,
                text,
                tag,
                "",
                nonce,
                subkey.*,
            ) catch return error.AuthenticationFailed,
            .chacha20_ietf_poly1305 => {
                std.crypto.aead.chacha_poly.ChaCha20Poly1305.decrypt(
                    text,
                    text,
                    tag,
                    "",
                    nonce,
                    subkey.*,
                ) catch return error.AuthenticationFailed;
            },
        }
    }
};

fn deriveMasterKey(password: []const u8, key_len: usize) [32]u8 {
    std.debug.assert(key_len == 16 or key_len == 32);
    var key = [_]u8{0} ** 32;
    var previous: [16]u8 = undefined;
    defer std.crypto.secureZero(u8, &previous);
    var offset: usize = 0;
    for (0..2) |round| {
        if (offset >= key_len) break;
        var md5 = std.crypto.hash.Md5.init(.{});
        if (round > 0) md5.update(&previous);
        md5.update(password);
        md5.final(&previous);
        const copy_len = @min(previous.len, key_len - offset);
        @memcpy(key[offset .. offset + copy_len], previous[0..copy_len]);
        offset += copy_len;
    }
    std.debug.assert(offset == key_len);
    return key;
}

const AddressKind = enum {
    ipv4,
    domain,
    ipv6,
};

const ParsedAddress = struct {
    kind: AddressKind,
    host: []const u8,
    port: u16,
    raw: []const u8,
};

const AddressPayload = struct {
    address: ParsedAddress,
    payload: []const u8,
};

fn parseAddressPayload(input: []const u8) !AddressPayload {
    if (input.len < 1) return error.TruncatedAddress;
    const address_len: usize = switch (input[0]) {
        0x01 => 1 + 4 + 2,
        0x03 => length: {
            if (input.len < 2) return error.TruncatedAddress;
            const domain_len: usize = input[1];
            if (domain_len == 0) return error.InvalidDomainLength;
            break :length std.math.add(
                usize,
                1 + 1 + 2,
                domain_len,
            ) catch return error.TruncatedAddress;
        },
        0x04 => 1 + 16 + 2,
        else => return error.InvalidAddressType,
    };
    if (address_len > address_size_max) return error.AddressTooLong;
    if (input.len < address_len) return error.TruncatedAddress;

    const host = switch (input[0]) {
        0x01 => input[1..5],
        0x03 => input[2 .. 2 + @as(usize, input[1])],
        0x04 => input[1..17],
        else => unreachable,
    };
    const port = std.mem.readInt(
        u16,
        input[address_len - 2 ..][0..2],
        .big,
    );
    return .{
        .address = .{
            .kind = switch (input[0]) {
                0x01 => .ipv4,
                0x03 => .domain,
                0x04 => .ipv6,
                else => unreachable,
            },
            .host = host,
            .port = port,
            .raw = input[0..address_len],
        },
        .payload = input[address_len..],
    };
}

fn parseSocksUdp(input: []const u8) !AddressPayload {
    if (input.len > wire_size_max) return error.DatagramTooLarge;
    if (input.len < 3) return error.TruncatedSocksDatagram;
    if (input[0] != 0 or input[1] != 0) return error.ReservedNotZero;
    if (input[2] != 0) return error.FragmentationNotSupported;
    return parseAddressPayload(input[3..]);
}

const Endpoint4 = struct {
    ip: [4]u8,
    port: u16,
};

const Endpoint6 = struct {
    ip: [16]u8,
    port: u16,
};

fn buildSocksUdpIpv4(
    output: []u8,
    target: Endpoint4,
    payload: []const u8,
) ![]u8 {
    const header_len: usize = 3 + 1 + 4 + 2;
    const total_len = std.math.add(
        usize,
        header_len,
        payload.len,
    ) catch return error.DatagramTooLarge;
    if (total_len > wire_size_max) return error.DatagramTooLarge;
    if (output.len < total_len) return error.OutputTooSmall;
    output[0..10].* = .{
        0,
        0,
        0,
        1,
        target.ip[0],
        target.ip[1],
        target.ip[2],
        target.ip[3],
        @intCast(target.port >> 8),
        @intCast(target.port & 0xff),
    };
    @memcpy(output[header_len..total_len], payload);
    return output[0..total_len];
}

fn buildSocksUdpIpv6(
    output: []u8,
    target: Endpoint6,
    payload: []const u8,
) ![]u8 {
    const header_len: usize = 3 + 1 + 16 + 2;
    const total_len = std.math.add(
        usize,
        header_len,
        payload.len,
    ) catch return error.DatagramTooLarge;
    if (total_len > wire_size_max) return error.DatagramTooLarge;
    if (output.len < total_len) return error.OutputTooSmall;
    @memset(output[0..3], 0);
    output[3] = 4;
    @memcpy(output[4..20], &target.ip);
    output[20] = @intCast(target.port >> 8);
    output[21] = @intCast(target.port & 0xff);
    @memcpy(output[header_len..total_len], payload);
    return output[0..total_len];
}

fn buildSocksUdpDomain(
    output: []u8,
    domain: []const u8,
    port: u16,
    payload: []const u8,
) ![]u8 {
    if (domain.len == 0 or domain.len > domain_size_max) {
        return error.InvalidDomainLength;
    }
    const address_len = std.math.add(
        usize,
        1 + 1 + 2,
        domain.len,
    ) catch return error.DatagramTooLarge;
    const payload_start = std.math.add(
        usize,
        3,
        address_len,
    ) catch return error.DatagramTooLarge;
    const total_len = std.math.add(
        usize,
        payload_start,
        payload.len,
    ) catch return error.DatagramTooLarge;
    if (total_len > wire_size_max) return error.DatagramTooLarge;
    if (output.len < total_len) return error.OutputTooSmall;

    output[0..5].* = .{ 0, 0, 0, 3, @intCast(domain.len) };
    @memcpy(output[5 .. 5 + domain.len], domain);
    output[payload_start - 2] = @intCast(port >> 8);
    output[payload_start - 1] = @intCast(port & 0xff);
    @memcpy(output[payload_start..total_len], payload);
    return output[0..total_len];
}

fn parseAssociateReply(reply: []const u8) !Endpoint4 {
    if (reply.len != 10) return error.InvalidAssociateReply;
    if (reply[0] != 5 or reply[2] != 0) return error.InvalidAssociateReply;
    if (reply[1] != 0) return error.AssociateRejected;
    if (reply[3] != 1) return error.NonIpv4AssociateReply;
    const port = std.mem.readInt(u16, reply[8..10], .big);
    if (port == 0) return error.InvalidAssociateReply;
    return .{
        .ip = reply[4..8].*,
        .port = port,
    };
}

fn mainServe(io: std.Io, args: []const []const u8) !void {
    if (args.len != 6 and args.len != 7) return error.InvalidArguments;
    const cipher = Cipher.parse(args[2]) orelse return error.InvalidArguments;
    const password = args[3];
    if (password.len == 0 or password.len > password_size_max) {
        return error.InvalidArguments;
    }
    const mode: ServeMode = if (std.mem.eql(u8, args[4], "normal"))
        .normal
    else if (std.mem.eql(u8, args[4], "bad-tag-once"))
        .bad_tag_once
    else if (std.mem.eql(u8, args[4], "truncated-salt-once"))
        .truncated_salt_once
    else if (std.mem.eql(u8, args[4], "truncated-tag-once"))
        .truncated_tag_once
    else
        return error.InvalidArguments;
    const endpoint_id = args[5];
    if (!validEndpointId(endpoint_id)) return error.InvalidArguments;
    const port = if (args.len == 7) try parsePortAllowZero(args[6]) else 0;
    try serveOracle(io, cipher, password, mode, endpoint_id, port);
}

fn mainEcho(io: std.Io, args: []const []const u8) !void {
    if (args.len != 3 and args.len != 4) return error.InvalidArguments;
    const family: EchoFamily = if (std.mem.eql(u8, args[2], "ipv4"))
        .ipv4
    else if (std.mem.eql(u8, args[2], "ipv6"))
        .ipv6
    else
        return error.InvalidArguments;
    const port = if (args.len == 4) try parsePortAllowZero(args[3]) else 0;
    try serveEcho(io, family, port);
}

fn mainProbe(io: std.Io, args: []const []const u8) ![]const u8 {
    if (args.len < 4) return error.InvalidArguments;
    const deadline = Deadline.after(io, probe_lifetime_ms);
    const probe_kind = parseProbeKind(args[2]) orelse return error.InvalidArguments;
    switch (probe_kind) {
        .roundtrip,
        .roundtrip_domain,
        .roundtrip_ipv6,
        .response_drop_recovery,
        .source_pin,
        .client_ip,
        .control_close,
        .selection_teardown,
        => {
            if (args.len != 6) return error.InvalidArguments;
            const mixed_port = try parsePort(args[3]);
            const target_port = try parsePort(args[4]);
            try validateNonceArgument(args[5]);
            switch (probe_kind) {
                .roundtrip => try probeRoundtrip(
                    io,
                    mixed_port,
                    target_port,
                    args[5],
                    deadline,
                ),
                .roundtrip_domain => try probeRoundtripDomain(
                    io,
                    mixed_port,
                    target_port,
                    args[5],
                    deadline,
                ),
                .roundtrip_ipv6 => try probeRoundtripIpv6(
                    io,
                    mixed_port,
                    target_port,
                    args[5],
                    deadline,
                ),
                .response_drop_recovery => try probeResponseDropRecovery(
                    io,
                    mixed_port,
                    target_port,
                    args[5],
                    deadline,
                ),
                .source_pin => try probeSourcePin(
                    io,
                    mixed_port,
                    target_port,
                    args[5],
                    deadline,
                ),
                .client_ip => try probeClientIp(
                    io,
                    mixed_port,
                    target_port,
                    args[5],
                    deadline,
                ),
                .control_close => try probeControlClose(
                    io,
                    mixed_port,
                    target_port,
                    args[5],
                    deadline,
                ),
                .selection_teardown => try probeSelectionTeardown(
                    io,
                    mixed_port,
                    target_port,
                    args[5],
                    deadline,
                ),
                else => unreachable,
            }
            return args[2];
        },
        .invalid_then_valid => {
            if (args.len != 7) return error.InvalidArguments;
            const invalid_kind = parseInvalidKind(args[3]) orelse
                return error.InvalidArguments;
            const mixed_port = try parsePort(args[4]);
            const target_port = try parsePort(args[5]);
            try validateNonceArgument(args[6]);
            try probeInvalidThenValid(
                io,
                invalid_kind,
                mixed_port,
                target_port,
                args[6],
                deadline,
            );
            return "invalid-then-valid";
        },
        .associate_rejected => {
            if (args.len != 5) return error.InvalidArguments;
            try probeAssociateRejected(
                io,
                try parsePort(args[3]),
                try parseReplyCode(args[4]),
                deadline,
            );
            return "associate-rejected";
        },
        .max => {
            if (args.len != 7) return error.InvalidArguments;
            const cipher = Cipher.parse(args[3]) orelse
                return error.InvalidArguments;
            const mixed_port = try parsePort(args[4]);
            const target_port = try parsePort(args[5]);
            try validateNonceArgument(args[6]);
            try probeMax(
                io,
                cipher,
                mixed_port,
                target_port,
                args[6],
                deadline,
            );
            return "max";
        },
        .capacity => {
            if (args.len != 4) return error.InvalidArguments;
            try probeCapacity(io, try parsePort(args[3]), deadline);
            return "capacity";
        },
    }
}

fn parseProbeKind(text: []const u8) ?ProbeKind {
    if (std.mem.eql(u8, text, "roundtrip")) return .roundtrip;
    if (std.mem.eql(u8, text, "roundtrip-domain")) return .roundtrip_domain;
    if (std.mem.eql(u8, text, "roundtrip-ipv6")) return .roundtrip_ipv6;
    if (std.mem.eql(u8, text, "response-drop-recovery")) {
        return .response_drop_recovery;
    }
    if (std.mem.eql(u8, text, "invalid-then-valid")) {
        return .invalid_then_valid;
    }
    if (std.mem.eql(u8, text, "source-pin")) return .source_pin;
    if (std.mem.eql(u8, text, "client-ip")) return .client_ip;
    if (std.mem.eql(u8, text, "control-close")) return .control_close;
    if (std.mem.eql(u8, text, "selection-teardown")) {
        return .selection_teardown;
    }
    if (std.mem.eql(u8, text, "associate-rejected")) {
        return .associate_rejected;
    }
    if (std.mem.eql(u8, text, "max")) return .max;
    if (std.mem.eql(u8, text, "capacity")) return .capacity;
    return null;
}

fn parseInvalidKind(text: []const u8) ?InvalidKind {
    if (std.mem.eql(u8, text, "rsv1")) return .rsv1;
    if (std.mem.eql(u8, text, "rsv2")) return .rsv2;
    if (std.mem.eql(u8, text, "frag")) return .frag;
    if (std.mem.eql(u8, text, "atyp")) return .atyp;
    if (std.mem.eql(u8, text, "truncated")) return .truncated;
    return null;
}

fn parseReplyCode(text: []const u8) !u8 {
    if (text.len == 0 or text.len > 3) return error.InvalidArguments;
    for (text) |byte| {
        if (!std.ascii.isDigit(byte)) return error.InvalidArguments;
    }
    return std.fmt.parseInt(u8, text, 10) catch
        return error.InvalidArguments;
}

fn parsePort(text: []const u8) !u16 {
    const port = try parsePortAllowZero(text);
    if (port == 0) return error.InvalidArguments;
    return port;
}

fn parsePortAllowZero(text: []const u8) !u16 {
    if (text.len == 0 or text.len > 5) return error.InvalidArguments;
    for (text) |byte| {
        if (!std.ascii.isDigit(byte)) return error.InvalidArguments;
    }
    return std.fmt.parseInt(u16, text, 10) catch
        return error.InvalidArguments;
}

fn validateNonceArgument(nonce: []const u8) !void {
    if (nonce.len == 0 or nonce.len > nonce_argument_size_max) {
        return error.InvalidArguments;
    }
}

fn validEndpointId(text: []const u8) bool {
    if (text.len == 0 or text.len > 32) return false;
    for (text) |byte| {
        if (std.ascii.isAlphanumeric(byte) or byte == '-' or byte == '_') {
            continue;
        }
        return false;
    }
    return true;
}

fn printLine(
    io: std.Io,
    comptime format: []const u8,
    arguments: anytype,
) !void {
    var buffer: [512]u8 = undefined;
    const line = try std.fmt.bufPrint(&buffer, format, arguments);
    // Streaming writes bypass seek-positioned buffering, so every marker is
    // visible immediately even when stdout is redirected to a regular file.
    try std.Io.File.stdout().writeStreamingAll(io, line);
}

fn serveOracle(
    io: std.Io,
    cipher: Cipher,
    password: []const u8,
    mode: ServeMode,
    endpoint_id: []const u8,
    requested_port: u16,
) !void {
    const fd = try createUdpSocket(requested_port);
    defer closeFd(fd);
    const endpoint = try socketName4(fd);
    try printLine(
        io,
        "E2E_SS_UDP_ORACLE_READY={s}:{d}\n",
        .{ endpoint_id, endpoint.port },
    );

    var crypto = DatagramCrypto.init(cipher, password);
    defer crypto.deinit();
    var receive_buffer: [receive_size_max]u8 = undefined;
    var plaintext_buffer: [wire_size_max]u8 = undefined;
    var response_buffer: [wire_size_max]u8 = undefined;
    const lifetime_deadline = Deadline.after(io, service_lifetime_ms);
    var pending_response: ?ResponseKind = switch (mode) {
        .normal => null,
        .bad_tag_once => .bad_tag,
        .truncated_salt_once => .truncated_salt,
        .truncated_tag_once => .truncated_tag,
    };

    var packet_count: u32 = 0;
    while (packet_count < packet_count_max) : (packet_count += 1) {
        const events = try waitFd(
            io,
            fd,
            std.posix.POLL.IN,
            lifetime_deadline,
        );
        if (events == 0) return;
        const received = receiveDatagram(fd, &receive_buffer) catch |err| {
            if (packetIoRecoverable(err)) continue;
            return err;
        };
        const raw_count = packet_count + 1;
        try printLine(
            io,
            "E2E_SS_UDP_ORACLE_RAW={s}:{d}\n",
            .{ endpoint_id, raw_count },
        );
        if (received.size > wire_size_max) continue;

        const plaintext = crypto.open(
            receive_buffer[0..received.size],
            &plaintext_buffer,
        ) catch continue;
        _ = parseAddressPayload(plaintext) catch continue;
        try printLine(
            io,
            "E2E_SS_UDP_ORACLE_VERIFIED={s}:{d}\n",
            .{ endpoint_id, raw_count },
        );

        const response = try crypto.sealRandom(
            io,
            plaintext,
            &response_buffer,
        );
        const response_kind = pending_response orelse .normal;
        const sent_response: []const u8 = switch (response_kind) {
            .normal => response,
            .bad_tag => corrupted: {
                std.debug.assert(response.len >= tag_size);
                response[response.len - 1] ^= 0x01;
                break :corrupted response;
            },
            .truncated_salt => response[0 .. crypto.cipher.saltLen() - 1],
            .truncated_tag => response[0 .. response.len - 1],
        };
        sendDatagram(
            io,
            fd,
            sent_response,
            received.sender,
            lifetime_deadline,
        ) catch |err| {
            if (packetIoRecoverable(err)) continue;
            return err;
        };
        if (response_kind != .normal) pending_response = null;
        try printLine(
            io,
            "E2E_SS_UDP_ORACLE_RESPONSE={s}:{d}:{s}\n",
            .{ endpoint_id, raw_count, response_kind.marker() },
        );
    }
}

fn serveEcho(io: std.Io, family: EchoFamily, requested_port: u16) !void {
    return switch (family) {
        .ipv4 => serveEcho4(io, requested_port),
        .ipv6 => serveEcho6(io, requested_port),
    };
}

fn serveEcho4(io: std.Io, requested_port: u16) !void {
    const fd = try createUdpSocket(requested_port);
    defer closeFd(fd);
    const endpoint = try socketName4(fd);
    try printLine(io, "E2E_UDP_ECHO_READY=ipv4:{d}\n", .{endpoint.port});

    var receive_buffer: [receive_size_max]u8 = undefined;
    const lifetime_deadline = Deadline.after(io, service_lifetime_ms);
    var packet_attempt_count: u32 = 0;
    var echoed_count: u32 = 0;
    while (packet_attempt_count < packet_count_max) : (packet_attempt_count += 1) {
        const events = try waitFd(
            io,
            fd,
            std.posix.POLL.IN,
            lifetime_deadline,
        );
        if (events == 0) return;
        const received = receiveDatagram(fd, &receive_buffer) catch |err| {
            if (packetIoRecoverable(err)) continue;
            return err;
        };
        if (received.size > wire_size_max) continue;
        sendDatagram(
            io,
            fd,
            receive_buffer[0..received.size],
            received.sender,
            lifetime_deadline,
        ) catch |err| {
            if (packetIoRecoverable(err)) continue;
            return err;
        };
        echoed_count += 1;
        try printLine(
            io,
            "E2E_UDP_ECHO_PACKET=ipv4:{d}\n",
            .{echoed_count},
        );
    }
}

fn serveEcho6(io: std.Io, requested_port: u16) !void {
    const fd = try createUdpSocket6(requested_port);
    defer closeFd(fd);
    const endpoint = try socketName6(fd);
    try printLine(io, "E2E_UDP_ECHO_READY=ipv6:{d}\n", .{endpoint.port});

    var receive_buffer: [receive_size_max]u8 = undefined;
    const lifetime_deadline = Deadline.after(io, service_lifetime_ms);
    var packet_attempt_count: u32 = 0;
    var echoed_count: u32 = 0;
    while (packet_attempt_count < packet_count_max) : (packet_attempt_count += 1) {
        const events = try waitFd(
            io,
            fd,
            std.posix.POLL.IN,
            lifetime_deadline,
        );
        if (events == 0) return;
        const received = receiveDatagram6(fd, &receive_buffer) catch |err| {
            if (packetIoRecoverable(err)) continue;
            return err;
        };
        if (received.size > wire_size_max) continue;
        sendDatagram6(
            io,
            fd,
            receive_buffer[0..received.size],
            received.sender,
            lifetime_deadline,
        ) catch |err| {
            if (packetIoRecoverable(err)) continue;
            return err;
        };
        echoed_count += 1;
        try printLine(
            io,
            "E2E_UDP_ECHO_PACKET=ipv6:{d}\n",
            .{echoed_count},
        );
    }
}

const Deadline = struct {
    expires_ms: i64,

    fn after(io: std.Io, duration_ms: i64) Deadline {
        std.debug.assert(duration_ms > 0);
        return .{
            .expires_ms = std.math.add(
                i64,
                monotonicMs(io),
                duration_ms,
            ) catch std.math.maxInt(i64),
        };
    }

    fn limited(self: Deadline, io: std.Io, duration_ms: i64) Deadline {
        const shorter = Deadline.after(io, duration_ms);
        return .{ .expires_ms = @min(self.expires_ms, shorter.expires_ms) };
    }

    fn remaining(self: Deadline, io: std.Io) !i32 {
        const now_ms = monotonicMs(io);
        if (now_ms >= self.expires_ms) return error.DeadlineExceeded;
        const difference = std.math.sub(
            i64,
            self.expires_ms,
            now_ms,
        ) catch return error.DeadlineExceeded;
        return @intCast(@min(difference, std.math.maxInt(i32)));
    }
};

fn monotonicMs(io: std.Io) i64 {
    return @intCast(@divTrunc(
        std.Io.Timestamp.now(io, .awake).nanoseconds,
        std.time.ns_per_ms,
    ));
}

fn waitFd(
    io: std.Io,
    fd: std.posix.fd_t,
    requested: i16,
    deadline: Deadline,
) !i16 {
    for (0..syscall_retry_max) |_| {
        const timeout_ms = deadline.remaining(io) catch |err| switch (err) {
            error.DeadlineExceeded => return 0,
        };
        var descriptor = [_]std.posix.pollfd{.{
            .fd = fd,
            .events = requested,
            .revents = 0,
        }};
        const result = std.c.poll(&descriptor, 1, timeout_ms);
        if (result == 0) {
            if (monotonicMs(io) >= deadline.expires_ms) return 0;
            continue;
        }
        if (result < 0) {
            switch (std.c.errno(result)) {
                .INTR => continue,
                .NOMEM => return error.SystemResources,
                else => return error.PollFailed,
            }
        }
        const events = descriptor[0].revents;
        if (events & std.posix.POLL.NVAL != 0) return error.InvalidSocket;
        if (events & (requested | std.posix.POLL.ERR |
            std.posix.POLL.HUP) == 0)
        {
            return error.UnexpectedPollEvent;
        }
        return events;
    }
    return error.SyscallRetryLimitExceeded;
}

fn waitFdPair(
    io: std.Io,
    first_fd: std.posix.fd_t,
    second_fd: std.posix.fd_t,
    deadline: Deadline,
) ![2]i16 {
    for (0..syscall_retry_max) |_| {
        const timeout_ms = deadline.remaining(io) catch |err| switch (err) {
            error.DeadlineExceeded => return .{ 0, 0 },
        };
        var descriptors = [_]std.posix.pollfd{
            .{ .fd = first_fd, .events = std.posix.POLL.IN, .revents = 0 },
            .{ .fd = second_fd, .events = std.posix.POLL.IN, .revents = 0 },
        };
        const result = std.c.poll(&descriptors, 2, timeout_ms);
        if (result == 0) {
            if (monotonicMs(io) >= deadline.expires_ms) return .{ 0, 0 };
            continue;
        }
        if (result < 0) {
            switch (std.c.errno(result)) {
                .INTR => continue,
                .NOMEM => return error.SystemResources,
                else => return error.PollFailed,
            }
        }
        for (descriptors) |descriptor| {
            if (descriptor.revents & std.posix.POLL.NVAL != 0) {
                return error.InvalidSocket;
            }
        }
        return .{ descriptors[0].revents, descriptors[1].revents };
    }
    return error.SyscallRetryLimitExceeded;
}

fn configureSocket(fd: std.posix.fd_t) !void {
    if (comptime builtin.os.tag.isDarwin()) {
        comptime if (!@hasDecl(std.c.SO, "NOSIGPIPE")) {
            @compileError("Darwin oracle sockets require SO_NOSIGPIPE");
        };
        var enabled: c_int = 1;
        if (std.c.setsockopt(
            fd,
            std.c.SOL.SOCKET,
            std.c.SO.NOSIGPIPE,
            std.mem.asBytes(&enabled),
            @sizeOf(c_int),
        ) != 0) return error.SocketSetupFailed;
    }

    const status_flags = std.c.fcntl(
        fd,
        std.posix.F.GETFL,
        @as(c_int, 0),
    );
    if (status_flags < 0) return error.SocketSetupFailed;
    const nonblocking: c_int = @bitCast(@as(u32, @bitCast(std.posix.O{
        .NONBLOCK = true,
    })));
    if (std.c.fcntl(
        fd,
        std.posix.F.SETFL,
        status_flags | nonblocking,
    ) < 0) return error.SocketSetupFailed;

    const descriptor_flags = std.c.fcntl(
        fd,
        std.posix.F.GETFD,
        @as(c_int, 0),
    );
    if (descriptor_flags < 0) return error.SocketSetupFailed;
    if (std.c.fcntl(
        fd,
        std.posix.F.SETFD,
        descriptor_flags | std.posix.FD_CLOEXEC,
    ) < 0) return error.SocketSetupFailed;
}

fn socketAddress4(endpoint: Endpoint4) std.c.sockaddr.in {
    var address = std.mem.zeroes(std.c.sockaddr.in);
    address.family = std.c.AF.INET;
    address.port = std.mem.nativeToBig(u16, endpoint.port);
    @memcpy(std.mem.asBytes(&address.addr)[0..4], &endpoint.ip);
    return address;
}

fn requireSocketBuffer(
    fd: std.posix.fd_t,
    option: u32,
    requested_size: c_int,
    minimum_size: c_int,
) !void {
    std.debug.assert(requested_size >= minimum_size);
    if (std.c.setsockopt(
        fd,
        std.c.SOL.SOCKET,
        option,
        std.mem.asBytes(&requested_size),
        @sizeOf(c_int),
    ) != 0) return error.SocketSetupFailed;

    var actual_size: c_int = 0;
    var actual_size_len: std.c.socklen_t = @sizeOf(c_int);
    if (std.c.getsockopt(
        fd,
        std.c.SOL.SOCKET,
        option,
        std.mem.asBytes(&actual_size).ptr,
        &actual_size_len,
    ) != 0) return error.SocketSetupFailed;
    if (actual_size_len != @sizeOf(c_int) or actual_size < minimum_size) {
        return error.SocketBufferTooSmall;
    }
}

fn configureUdpBuffers(fd: std.posix.fd_t) !void {
    const send_size = std.math.cast(c_int, wire_size_max) orelse
        return error.SocketSetupFailed;
    const receive_size = std.math.cast(c_int, 262_144) orelse
        return error.SocketSetupFailed;
    const receive_minimum = std.math.cast(c_int, receive_size_max) orelse
        return error.SocketSetupFailed;
    try requireSocketBuffer(fd, std.c.SO.SNDBUF, send_size, send_size);
    try requireSocketBuffer(
        fd,
        std.c.SO.RCVBUF,
        receive_size,
        receive_minimum,
    );
}

fn socketAddress6(endpoint: Endpoint6) std.c.sockaddr.in6 {
    var address = std.mem.zeroes(std.c.sockaddr.in6);
    address.family = std.c.AF.INET6;
    address.port = std.mem.nativeToBig(u16, endpoint.port);
    address.addr = endpoint.ip;
    return address;
}

fn createUdpSocketAt(ip: [4]u8, port: u16) !std.posix.fd_t {
    const fd = std.c.socket(
        std.c.AF.INET,
        std.c.SOCK.DGRAM,
        std.c.IPPROTO.UDP,
    );
    if (fd < 0) return error.SocketSetupFailed;
    errdefer closeFd(fd);
    try configureSocket(fd);
    try configureUdpBuffers(fd);
    const address = socketAddress4(.{ .ip = ip, .port = port });
    for (0..syscall_retry_max) |_| {
        const result = std.c.bind(
            fd,
            @ptrCast(&address),
            @sizeOf(std.c.sockaddr.in),
        );
        if (result == 0) return fd;
        if (std.c.errno(result) == .INTR) continue;
        return error.BindFailed;
    }
    return error.SyscallRetryLimitExceeded;
}

fn createUdpSocket(port: u16) !std.posix.fd_t {
    return createUdpSocketAt(.{ 127, 0, 0, 1 }, port);
}

fn discoverNonLoopbackIpv4() ![4]u8 {
    const fd = std.c.socket(
        std.c.AF.INET,
        std.c.SOCK.DGRAM,
        std.c.IPPROTO.UDP,
    );
    if (fd < 0) return error.SocketSetupFailed;
    defer closeFd(fd);
    try configureSocket(fd);
    const probe = socketAddress4(.{
        .ip = .{ 192, 0, 2, 1 },
        .port = 9,
    });
    for (0..syscall_retry_max) |_| {
        const result = std.c.connect(
            fd,
            @ptrCast(&probe),
            @sizeOf(std.c.sockaddr.in),
        );
        if (result == 0) break;
        if (std.c.errno(result) == .INTR) continue;
        return error.NonLoopbackAddressUnavailable;
    } else return error.SyscallRetryLimitExceeded;

    const endpoint = try socketName4(fd);
    if (endpoint.ip[0] == 0 or endpoint.ip[0] == 127) {
        return error.NonLoopbackAddressUnavailable;
    }
    return endpoint.ip;
}

fn createUdpSocket6(port: u16) !std.posix.fd_t {
    const fd = std.c.socket(
        std.c.AF.INET6,
        std.c.SOCK.DGRAM,
        std.c.IPPROTO.UDP,
    );
    if (fd < 0) return error.SocketSetupFailed;
    errdefer closeFd(fd);
    try configureSocket(fd);
    try configureUdpBuffers(fd);
    var enabled: c_int = 1;
    if (std.c.setsockopt(
        fd,
        std.posix.IPPROTO.IPV6,
        ipv6_v6only_option,
        std.mem.asBytes(&enabled),
        @sizeOf(c_int),
    ) != 0) return error.SocketSetupFailed;
    const address = socketAddress6(.{
        .ip = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 },
        .port = port,
    });
    for (0..syscall_retry_max) |_| {
        const result = std.c.bind(
            fd,
            @ptrCast(&address),
            @sizeOf(std.c.sockaddr.in6),
        );
        if (result == 0) return fd;
        if (std.c.errno(result) == .INTR) continue;
        return error.BindFailed;
    }
    return error.SyscallRetryLimitExceeded;
}

fn createTcpSocket() !std.posix.fd_t {
    const fd = std.c.socket(
        std.c.AF.INET,
        std.c.SOCK.STREAM,
        std.c.IPPROTO.TCP,
    );
    if (fd < 0) return error.SocketSetupFailed;
    errdefer closeFd(fd);
    try configureSocket(fd);
    return fd;
}

fn closeFd(fd: std.posix.fd_t) void {
    if (fd < 0) return;
    const result = std.c.close(fd);
    if (result == 0) return;
    // POSIX leaves descriptor state unspecified on EINTR; retrying can close a
    // reused descriptor, so every close outcome is terminal and handled once.
    switch (std.c.errno(result)) {
        .INTR, .BADF, .IO => return,
        else => return,
    }
}

fn socketName4(fd: std.posix.fd_t) !Endpoint4 {
    var address = std.mem.zeroes(std.c.sockaddr.in);
    var address_len: std.c.socklen_t = @sizeOf(std.c.sockaddr.in);
    for (0..syscall_retry_max) |_| {
        const result = std.c.getsockname(
            fd,
            @ptrCast(&address),
            &address_len,
        );
        if (result == 0) break;
        if (std.c.errno(result) == .INTR) continue;
        return error.GetSocketNameFailed;
    } else return error.SyscallRetryLimitExceeded;
    if (address_len < @sizeOf(std.c.sockaddr.in)) {
        return error.InvalidSocketAddress;
    }
    if (address.family != std.c.AF.INET) return error.InvalidSocketAddress;
    return .{
        .ip = std.mem.asBytes(&address.addr)[0..4].*,
        .port = std.mem.bigToNative(u16, address.port),
    };
}

fn socketName6(fd: std.posix.fd_t) !Endpoint6 {
    var address = std.mem.zeroes(std.c.sockaddr.in6);
    var address_len: std.c.socklen_t = @sizeOf(std.c.sockaddr.in6);
    for (0..syscall_retry_max) |_| {
        const result = std.c.getsockname(
            fd,
            @ptrCast(&address),
            &address_len,
        );
        if (result == 0) break;
        if (std.c.errno(result) == .INTR) continue;
        return error.GetSocketNameFailed;
    } else return error.SyscallRetryLimitExceeded;
    if (address_len < @sizeOf(std.c.sockaddr.in6)) {
        return error.InvalidSocketAddress;
    }
    if (address.family != std.c.AF.INET6) return error.InvalidSocketAddress;
    return .{
        .ip = address.addr,
        .port = std.mem.bigToNative(u16, address.port),
    };
}

const ReceivedDatagram = struct {
    size: usize,
    sender: Endpoint4,
};

fn receiveDatagram(
    fd: std.posix.fd_t,
    output: []u8,
) !ReceivedDatagram {
    const flags: c_int = if (@hasDecl(std.c.MSG, "TRUNC"))
        @intCast(std.c.MSG.TRUNC)
    else
        0;
    for (0..syscall_retry_max) |_| {
        var address = std.mem.zeroes(std.c.sockaddr.in);
        var address_len: std.c.socklen_t = @sizeOf(std.c.sockaddr.in);
        const result = std.c.recvfrom(
            fd,
            output.ptr,
            output.len,
            flags,
            @ptrCast(&address),
            &address_len,
        );
        if (result >= 0) {
            if (address_len < @sizeOf(std.c.sockaddr.in)) {
                return error.PacketDropped;
            }
            if (address.family != std.c.AF.INET) return error.PacketDropped;
            return .{
                .size = @intCast(result),
                .sender = .{
                    .ip = std.mem.asBytes(&address.addr)[0..4].*,
                    .port = std.mem.bigToNative(u16, address.port),
                },
            };
        }
        switch (std.c.errno(result)) {
            .INTR => continue,
            .AGAIN => return error.WouldBlock,
            .MSGSIZE => return error.DatagramTooLarge,
            .CONNREFUSED,
            .CONNRESET,
            .HOSTUNREACH,
            .NETUNREACH,
            .NOBUFS,
            .NOMEM,
            .PIPE,
            .TIMEDOUT,
            => return error.PacketDropped,
            else => return error.ReceiveFailed,
        }
    }
    return error.SyscallRetryLimitExceeded;
}

const ReceivedDatagram6 = struct {
    size: usize,
    sender: Endpoint6,
};

fn receiveDatagram6(
    fd: std.posix.fd_t,
    output: []u8,
) !ReceivedDatagram6 {
    const flags: c_int = if (@hasDecl(std.c.MSG, "TRUNC"))
        @intCast(std.c.MSG.TRUNC)
    else
        0;
    for (0..syscall_retry_max) |_| {
        var address = std.mem.zeroes(std.c.sockaddr.in6);
        var address_len: std.c.socklen_t = @sizeOf(std.c.sockaddr.in6);
        const result = std.c.recvfrom(
            fd,
            output.ptr,
            output.len,
            flags,
            @ptrCast(&address),
            &address_len,
        );
        if (result >= 0) {
            if (address_len < @sizeOf(std.c.sockaddr.in6) or
                address.family != std.c.AF.INET6)
            {
                return error.PacketDropped;
            }
            return .{
                .size = @intCast(result),
                .sender = .{
                    .ip = address.addr,
                    .port = std.mem.bigToNative(u16, address.port),
                },
            };
        }
        switch (std.c.errno(result)) {
            .INTR => continue,
            .AGAIN => return error.WouldBlock,
            .MSGSIZE => return error.DatagramTooLarge,
            .CONNREFUSED,
            .CONNRESET,
            .HOSTUNREACH,
            .NETUNREACH,
            .NOBUFS,
            .NOMEM,
            .PIPE,
            .TIMEDOUT,
            => return error.PacketDropped,
            else => return error.ReceiveFailed,
        }
    }
    return error.SyscallRetryLimitExceeded;
}

fn sendDatagram6(
    io: std.Io,
    fd: std.posix.fd_t,
    bytes: []const u8,
    destination: Endpoint6,
    deadline: Deadline,
) !void {
    if (bytes.len > wire_size_max) return error.DatagramTooLarge;
    const address = socketAddress6(destination);
    const flags: c_int = if (@hasDecl(std.c.MSG, "NOSIGNAL"))
        @intCast(std.c.MSG.NOSIGNAL)
    else
        0;
    for (0..syscall_retry_max) |_| {
        const events = try waitFd(io, fd, std.posix.POLL.OUT, deadline);
        if (events == 0) return error.DeadlineExceeded;
        const result = std.c.sendto(
            fd,
            bytes.ptr,
            bytes.len,
            flags,
            @ptrCast(&address),
            @sizeOf(std.c.sockaddr.in6),
        );
        if (result >= 0) {
            if (@as(usize, @intCast(result)) != bytes.len) {
                return error.PartialDatagram;
            }
            return;
        }
        switch (std.c.errno(result)) {
            .INTR, .AGAIN => continue,
            .MSGSIZE => return error.DatagramTooLarge,
            .CONNREFUSED,
            .CONNRESET,
            .HOSTUNREACH,
            .NETUNREACH,
            .NOBUFS,
            .NOMEM,
            .PIPE,
            .TIMEDOUT,
            => return error.PacketDropped,
            else => return error.SendFailed,
        }
    }
    return error.SyscallRetryLimitExceeded;
}

fn sendDatagram(
    io: std.Io,
    fd: std.posix.fd_t,
    bytes: []const u8,
    destination: Endpoint4,
    deadline: Deadline,
) !void {
    if (bytes.len > wire_size_max) return error.DatagramTooLarge;
    const address = socketAddress4(destination);
    const flags: c_int = if (@hasDecl(std.c.MSG, "NOSIGNAL"))
        @intCast(std.c.MSG.NOSIGNAL)
    else
        0;
    for (0..syscall_retry_max) |_| {
        const events = try waitFd(io, fd, std.posix.POLL.OUT, deadline);
        if (events == 0) return error.DeadlineExceeded;
        const result = std.c.sendto(
            fd,
            bytes.ptr,
            bytes.len,
            flags,
            @ptrCast(&address),
            @sizeOf(std.c.sockaddr.in),
        );
        if (result >= 0) {
            if (@as(usize, @intCast(result)) != bytes.len) {
                return error.PartialDatagram;
            }
            return;
        }
        switch (std.c.errno(result)) {
            .INTR, .AGAIN => continue,
            .MSGSIZE => return error.DatagramTooLarge,
            .CONNREFUSED,
            .CONNRESET,
            .HOSTUNREACH,
            .NETUNREACH,
            .NOBUFS,
            .NOMEM,
            .PIPE,
            .TIMEDOUT,
            => return error.PacketDropped,
            else => return error.SendFailed,
        }
    }
    return error.SyscallRetryLimitExceeded;
}

fn packetIoRecoverable(err: anyerror) bool {
    return switch (err) {
        error.WouldBlock,
        error.DatagramTooLarge,
        error.PacketDropped,
        => true,
        else => false,
    };
}

fn connectTcpLoopback(
    io: std.Io,
    port: u16,
    deadline: Deadline,
) !std.posix.fd_t {
    const fd = try createTcpSocket();
    errdefer closeFd(fd);
    const address = socketAddress4(.{
        .ip = .{ 127, 0, 0, 1 },
        .port = port,
    });
    for (0..syscall_retry_max) |_| {
        const result = std.c.connect(
            fd,
            @ptrCast(&address),
            @sizeOf(std.c.sockaddr.in),
        );
        if (result == 0) return fd;
        switch (std.c.errno(result)) {
            .INTR => continue,
            .ISCONN => return fd,
            .INPROGRESS, .ALREADY, .AGAIN => break,
            .CONNREFUSED => return error.ConnectionRefused,
            else => return error.ConnectFailed,
        }
    } else return error.SyscallRetryLimitExceeded;

    const events = try waitFd(io, fd, std.posix.POLL.OUT, deadline);
    if (events == 0) return error.DeadlineExceeded;
    var socket_error: c_int = 0;
    var socket_error_len: std.c.socklen_t = @sizeOf(c_int);
    if (std.c.getsockopt(
        fd,
        std.c.SOL.SOCKET,
        std.c.SO.ERROR,
        &socket_error,
        &socket_error_len,
    ) != 0) return error.ConnectFailed;
    if (socket_error != 0) return error.ConnectFailed;
    return fd;
}

fn sendStreamAll(
    io: std.Io,
    fd: std.posix.fd_t,
    bytes: []const u8,
    deadline: Deadline,
) !void {
    const flags: c_int = if (@hasDecl(std.c.MSG, "NOSIGNAL"))
        @intCast(std.c.MSG.NOSIGNAL)
    else
        0;
    var offset: usize = 0;
    var iteration: usize = 0;
    while (offset < bytes.len and iteration < stream_io_iteration_max) : (iteration += 1) {
        const events = try waitFd(io, fd, std.posix.POLL.OUT, deadline);
        if (events == 0) return error.DeadlineExceeded;
        const result = std.c.send(
            fd,
            bytes[offset..].ptr,
            bytes.len - offset,
            flags,
        );
        if (result > 0) {
            offset = std.math.add(
                usize,
                offset,
                @intCast(result),
            ) catch return error.StreamWriteFailed;
            continue;
        }
        if (result == 0) return error.StreamWriteZero;
        switch (std.c.errno(result)) {
            .INTR, .AGAIN => continue,
            .PIPE => return error.BrokenPipe,
            .CONNRESET => return error.ConnectionReset,
            else => return error.StreamWriteFailed,
        }
    }
    if (offset != bytes.len) return error.StreamIterationLimitExceeded;
}

fn receiveStreamExact(
    io: std.Io,
    fd: std.posix.fd_t,
    output: []u8,
    deadline: Deadline,
) !void {
    var offset: usize = 0;
    var iteration: usize = 0;
    while (offset < output.len and iteration < stream_io_iteration_max) : (iteration += 1) {
        const events = try waitFd(io, fd, std.posix.POLL.IN, deadline);
        if (events == 0) return error.DeadlineExceeded;
        const result = std.c.recv(
            fd,
            output[offset..].ptr,
            output.len - offset,
            0,
        );
        if (result > 0) {
            offset = std.math.add(
                usize,
                offset,
                @intCast(result),
            ) catch return error.StreamReadFailed;
            continue;
        }
        if (result == 0) return error.UnexpectedEof;
        switch (std.c.errno(result)) {
            .INTR, .AGAIN => continue,
            .CONNRESET => return error.ConnectionReset,
            else => return error.StreamReadFailed,
        }
    }
    if (offset != output.len) return error.StreamIterationLimitExceeded;
}

fn shutdownControlWrite(fd: std.posix.fd_t) !void {
    for (0..syscall_retry_max) |_| {
        const result = std.c.shutdown(fd, std.c.SHUT.WR);
        if (result == 0) return;
        switch (std.c.errno(result)) {
            .INTR => continue,
            .NOTCONN => return,
            else => return error.ControlShutdownFailed,
        }
    }
    return error.SyscallRetryLimitExceeded;
}

fn waitForControlEof(
    io: std.Io,
    fd: std.posix.fd_t,
    deadline: Deadline,
) !void {
    var byte: [1]u8 = undefined;
    for (0..syscall_retry_max) |_| {
        const events = try waitFd(io, fd, std.posix.POLL.IN, deadline);
        if (events == 0) return error.DeadlineExceeded;
        const result = std.c.recv(fd, &byte, byte.len, 0);
        if (result == 0) return;
        if (result > 0) return error.UnexpectedControlData;
        switch (std.c.errno(result)) {
            .INTR, .AGAIN => continue,
            .CONNRESET => return,
            else => return error.StreamReadFailed,
        }
    }
    return error.SyscallRetryLimitExceeded;
}

fn completeControlTeardown(
    io: std.Io,
    fd: *std.posix.fd_t,
    deadline: Deadline,
) !void {
    if (fd.* < 0) return;
    try shutdownControlWrite(fd.*);
    try waitForControlEof(io, fd.*, deadline);
    closeFd(fd.*);
    fd.* = -1;
}

const AssociationResult = struct {
    fd: std.posix.fd_t,
    rep: u8,
    relay: ?Endpoint4,
};

fn establishAssociation(
    io: std.Io,
    mixed_port: u16,
    deadline: Deadline,
) !AssociationResult {
    const fd = try connectTcpLoopback(io, mixed_port, deadline);
    errdefer closeFd(fd);

    try sendStreamAll(io, fd, &.{ 5, 1, 0 }, deadline);
    var greeting_reply: [2]u8 = undefined;
    try receiveStreamExact(io, fd, &greeting_reply, deadline);
    if (!std.mem.eql(u8, &greeting_reply, &.{ 5, 0 })) {
        return error.InvalidGreetingReply;
    }

    try sendStreamAll(
        io,
        fd,
        &.{ 5, 3, 0, 1, 0, 0, 0, 0, 0, 0 },
        deadline,
    );
    var reply: [10]u8 = undefined;
    try receiveStreamExact(io, fd, &reply, deadline);
    if (reply[0] != 5 or reply[2] != 0) {
        return error.InvalidAssociateReply;
    }
    if (reply[3] != 1) return error.NonIpv4AssociateReply;
    if (reply[1] != 0) {
        return .{ .fd = fd, .rep = reply[1], .relay = null };
    }
    return .{
        .fd = fd,
        .rep = 0,
        .relay = try parseAssociateReply(&reply),
    };
}

fn openAssociation(
    io: std.Io,
    mixed_port: u16,
    deadline: Deadline,
) !AssociationResult {
    const result = try establishAssociation(io, mixed_port, deadline);
    errdefer closeFd(result.fd);
    if (result.rep != 0) return error.AssociateRejected;
    const relay = result.relay orelse return error.InvalidAssociateReply;
    if (!std.mem.eql(u8, &relay.ip, &.{ 127, 0, 0, 1 })) {
        return error.NonLoopbackRelay;
    }
    return result;
}

fn validateRelayResponse(
    received: ReceivedDatagram,
    expected_relay: Endpoint4,
    bytes: []const u8,
    expected_target: Endpoint4,
    expected_payload: []const u8,
) !void {
    if (!endpointEqual(received.sender, expected_relay)) {
        return error.UnexpectedResponseSender;
    }
    if (received.size > bytes.len) return error.DatagramTooLarge;
    const parsed = try parseSocksUdp(bytes[0..received.size]);
    if (parsed.address.kind != .ipv4) return error.UnexpectedResponseAddress;
    if (!std.mem.eql(u8, parsed.address.host, &expected_target.ip)) {
        return error.UnexpectedResponseAddress;
    }
    if (parsed.address.port != expected_target.port) {
        return error.UnexpectedResponseAddress;
    }
    if (!std.mem.eql(u8, parsed.payload, expected_payload)) {
        return error.UnexpectedResponsePayload;
    }
}

fn validateDomainRelayResponse(
    received: ReceivedDatagram,
    expected_relay: Endpoint4,
    bytes: []const u8,
    expected_domain: []const u8,
    expected_port: u16,
    expected_payload: []const u8,
) !void {
    if (!endpointEqual(received.sender, expected_relay)) {
        return error.UnexpectedResponseSender;
    }
    if (received.size > bytes.len) return error.DatagramTooLarge;
    const parsed = try parseSocksUdp(bytes[0..received.size]);
    if (parsed.address.kind != .domain) return error.UnexpectedResponseAddress;
    if (!std.mem.eql(u8, parsed.address.host, expected_domain)) {
        return error.UnexpectedResponseAddress;
    }
    if (parsed.address.port != expected_port) {
        return error.UnexpectedResponseAddress;
    }
    if (!std.mem.eql(u8, parsed.payload, expected_payload)) {
        return error.UnexpectedResponsePayload;
    }
}

fn validateLoopbackRelayResponse(
    received: ReceivedDatagram,
    expected_relay: Endpoint4,
    bytes: []const u8,
    expected_port: u16,
    expected_payload: []const u8,
) !void {
    if (!endpointEqual(received.sender, expected_relay)) {
        return error.UnexpectedResponseSender;
    }
    if (received.size > bytes.len) return error.DatagramTooLarge;
    const parsed = try parseSocksUdp(bytes[0..received.size]);
    const is_loopback = switch (parsed.address.kind) {
        .ipv4 => std.mem.eql(u8, parsed.address.host, &.{ 127, 0, 0, 1 }),
        .ipv6 => std.mem.eql(
            u8,
            parsed.address.host,
            &.{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 },
        ),
        .domain => std.ascii.eqlIgnoreCase(parsed.address.host, "localhost"),
    };
    if (!is_loopback or parsed.address.port != expected_port) {
        return error.UnexpectedResponseAddress;
    }
    if (!std.mem.eql(u8, parsed.payload, expected_payload)) {
        return error.UnexpectedResponsePayload;
    }
}

fn validateIpv6RelayResponse(
    received: ReceivedDatagram,
    expected_relay: Endpoint4,
    bytes: []const u8,
    expected_target: Endpoint6,
    expected_payload: []const u8,
) !void {
    if (!endpointEqual(received.sender, expected_relay)) {
        return error.UnexpectedResponseSender;
    }
    if (received.size > bytes.len) return error.DatagramTooLarge;
    const parsed = try parseSocksUdp(bytes[0..received.size]);
    if (parsed.address.kind != .ipv6 or
        !std.mem.eql(u8, parsed.address.host, &expected_target.ip) or
        parsed.address.port != expected_target.port)
    {
        return error.UnexpectedResponseAddress;
    }
    if (!std.mem.eql(u8, parsed.payload, expected_payload)) {
        return error.UnexpectedResponsePayload;
    }
}

fn endpointEqual(left: Endpoint4, right: Endpoint4) bool {
    return left.port == right.port and std.mem.eql(u8, &left.ip, &right.ip);
}

fn receiveRelayResponse(
    io: std.Io,
    fd: std.posix.fd_t,
    output: []u8,
    deadline: Deadline,
) !ReceivedDatagram {
    const events = try waitFd(io, fd, std.posix.POLL.IN, deadline);
    if (events == 0) return error.DeadlineExceeded;
    return receiveDatagram(fd, output);
}

fn expectNoResponse(
    io: std.Io,
    fd: std.posix.fd_t,
    deadline: Deadline,
) !void {
    var unexpected: [receive_size_max]u8 = undefined;
    for (0..syscall_retry_max) |_| {
        const events = try waitFd(io, fd, std.posix.POLL.IN, deadline);
        if (events == 0) return;
        _ = receiveDatagram(fd, &unexpected) catch |err| {
            if (packetIoRecoverable(err)) continue;
            return err;
        };
        return error.UnexpectedUdpResponse;
    }
    return error.SyscallRetryLimitExceeded;
}

fn drainNoResponseFd(fd: std.posix.fd_t, buffer: []u8) !void {
    _ = receiveDatagram(fd, buffer) catch |err| {
        if (packetIoRecoverable(err)) return;
        return err;
    };
    return error.UnexpectedUdpResponse;
}

fn expectNoResponsePair(
    io: std.Io,
    first_fd: std.posix.fd_t,
    second_fd: std.posix.fd_t,
    deadline: Deadline,
) !void {
    var unexpected: [receive_size_max]u8 = undefined;
    for (0..syscall_retry_max) |_| {
        const events = try waitFdPair(io, first_fd, second_fd, deadline);
        if (events[0] == 0 and events[1] == 0) return;
        if (events[0] != 0) try drainNoResponseFd(first_fd, &unexpected);
        if (events[1] != 0) try drainNoResponseFd(second_fd, &unexpected);
    }
    return error.SyscallRetryLimitExceeded;
}

fn sendAndExpectIpv4(
    io: std.Io,
    udp_fd: std.posix.fd_t,
    relay: Endpoint4,
    target: Endpoint4,
    payload: []const u8,
    deadline: Deadline,
) !void {
    var request_buffer: [wire_size_max]u8 = undefined;
    const request = try buildSocksUdpIpv4(
        &request_buffer,
        target,
        payload,
    );
    try sendDatagram(io, udp_fd, request, relay, deadline);
    var response_buffer: [receive_size_max]u8 = undefined;
    const response = try receiveRelayResponse(
        io,
        udp_fd,
        &response_buffer,
        deadline,
    );
    try validateRelayResponse(
        response,
        relay,
        &response_buffer,
        target,
        payload,
    );
}

fn sendAndExpectDomain(
    io: std.Io,
    udp_fd: std.posix.fd_t,
    relay: Endpoint4,
    target_port: u16,
    payload: []const u8,
    deadline: Deadline,
) !void {
    var request_buffer: [wire_size_max]u8 = undefined;
    const request = try buildSocksUdpDomain(
        &request_buffer,
        "localhost",
        target_port,
        payload,
    );
    try sendDatagram(io, udp_fd, request, relay, deadline);
    var response_buffer: [receive_size_max]u8 = undefined;
    const response = try receiveRelayResponse(
        io,
        udp_fd,
        &response_buffer,
        deadline,
    );
    try validateLoopbackRelayResponse(
        response,
        relay,
        &response_buffer,
        target_port,
        payload,
    );
}

fn sendAndExpectIpv6(
    io: std.Io,
    udp_fd: std.posix.fd_t,
    relay: Endpoint4,
    target: Endpoint6,
    payload: []const u8,
    deadline: Deadline,
) !void {
    var request_buffer: [wire_size_max]u8 = undefined;
    const request = try buildSocksUdpIpv6(&request_buffer, target, payload);
    try sendDatagram(io, udp_fd, request, relay, deadline);
    var response_buffer: [receive_size_max]u8 = undefined;
    const response = try receiveRelayResponse(
        io,
        udp_fd,
        &response_buffer,
        deadline,
    );
    try validateIpv6RelayResponse(
        response,
        relay,
        &response_buffer,
        target,
        payload,
    );
}

fn makeInvalidPacket(
    kind: InvalidKind,
    output: []u8,
    target: Endpoint4,
    payload: []const u8,
) ![]const u8 {
    const valid = try buildSocksUdpIpv4(output, target, payload);
    switch (kind) {
        .rsv1 => output[0] = 1,
        .rsv2 => output[1] = 1,
        .frag => output[2] = 1,
        .atyp => output[3] = 2,
        .truncated => return output[0..5],
    }
    return valid;
}

fn taggedPayload(
    output: []u8,
    nonce: []const u8,
    tag: []const u8,
) ![]const u8 {
    const total_len = std.math.add(
        usize,
        nonce.len,
        tag.len,
    ) catch return error.OutputTooSmall;
    if (total_len > output.len) return error.OutputTooSmall;
    @memcpy(output[0..nonce.len], nonce);
    @memcpy(output[nonce.len..total_len], tag);
    return output[0..total_len];
}

fn probeRoundtrip(
    io: std.Io,
    mixed_port: u16,
    target_port: u16,
    nonce: []const u8,
    deadline: Deadline,
) !void {
    const association = try openAssociation(io, mixed_port, deadline);
    defer closeFd(association.fd);
    const relay = association.relay.?;
    const udp_fd = try createUdpSocket(0);
    defer closeFd(udp_fd);
    try sendAndExpectIpv4(
        io,
        udp_fd,
        relay,
        .{ .ip = .{ 127, 0, 0, 1 }, .port = target_port },
        nonce,
        deadline,
    );
}

fn probeRoundtripDomain(
    io: std.Io,
    mixed_port: u16,
    target_port: u16,
    nonce: []const u8,
    deadline: Deadline,
) !void {
    const association = try openAssociation(io, mixed_port, deadline);
    defer closeFd(association.fd);
    const udp_fd = try createUdpSocket(0);
    defer closeFd(udp_fd);
    try sendAndExpectDomain(
        io,
        udp_fd,
        association.relay.?,
        target_port,
        nonce,
        deadline,
    );
}

fn probeRoundtripIpv6(
    io: std.Io,
    mixed_port: u16,
    target_port: u16,
    nonce: []const u8,
    deadline: Deadline,
) !void {
    const association = try openAssociation(io, mixed_port, deadline);
    defer closeFd(association.fd);
    const udp_fd = try createUdpSocket(0);
    defer closeFd(udp_fd);
    try sendAndExpectIpv6(
        io,
        udp_fd,
        association.relay.?,
        .{
            .ip = .{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 },
            .port = target_port,
        },
        nonce,
        deadline,
    );
}

fn probeResponseDropRecovery(
    io: std.Io,
    mixed_port: u16,
    target_port: u16,
    nonce: []const u8,
    deadline: Deadline,
) !void {
    const association = try openAssociation(io, mixed_port, deadline);
    defer closeFd(association.fd);
    const relay = association.relay.?;
    const udp_fd = try createUdpSocket(0);
    defer closeFd(udp_fd);
    const target = Endpoint4{
        .ip = .{ 127, 0, 0, 1 },
        .port = target_port,
    };
    var first_payload_buffer: [tagged_payload_size_max]u8 = undefined;
    const first_payload = try taggedPayload(
        &first_payload_buffer,
        nonce,
        "-first",
    );
    var request_buffer: [wire_size_max]u8 = undefined;
    const request = try buildSocksUdpIpv4(
        &request_buffer,
        target,
        first_payload,
    );
    try sendDatagram(io, udp_fd, request, relay, deadline);
    try expectNoResponse(
        io,
        udp_fd,
        deadline.limited(io, absence_window_ms),
    );
    try sendAndExpectIpv4(
        io,
        udp_fd,
        relay,
        target,
        nonce,
        deadline,
    );
}

fn probeInvalidThenValid(
    io: std.Io,
    invalid_kind: InvalidKind,
    mixed_port: u16,
    target_port: u16,
    nonce: []const u8,
    deadline: Deadline,
) !void {
    const association = try openAssociation(io, mixed_port, deadline);
    defer closeFd(association.fd);
    const relay = association.relay.?;
    const udp_fd = try createUdpSocket(0);
    defer closeFd(udp_fd);
    const target = Endpoint4{
        .ip = .{ 127, 0, 0, 1 },
        .port = target_port,
    };
    var invalid_payload_buffer: [tagged_payload_size_max]u8 = undefined;
    const invalid_payload = try taggedPayload(
        &invalid_payload_buffer,
        nonce,
        "-invalid",
    );
    var invalid_buffer: [wire_size_max]u8 = undefined;
    const invalid = try makeInvalidPacket(
        invalid_kind,
        &invalid_buffer,
        target,
        invalid_payload,
    );
    try sendDatagram(io, udp_fd, invalid, relay, deadline);
    try expectNoResponse(
        io,
        udp_fd,
        deadline.limited(io, absence_window_ms),
    );
    try sendAndExpectIpv4(
        io,
        udp_fd,
        relay,
        target,
        nonce,
        deadline,
    );
}

fn probeSourcePin(
    io: std.Io,
    mixed_port: u16,
    target_port: u16,
    nonce: []const u8,
    deadline: Deadline,
) !void {
    const association = try openAssociation(io, mixed_port, deadline);
    defer closeFd(association.fd);
    const relay = association.relay.?;
    const first_fd = try createUdpSocket(0);
    defer closeFd(first_fd);
    const second_fd = try createUdpSocket(0);
    defer closeFd(second_fd);
    const target = Endpoint4{
        .ip = .{ 127, 0, 0, 1 },
        .port = target_port,
    };

    var payload_buffer: [tagged_payload_size_max]u8 = undefined;
    const invalid_payload = try taggedPayload(
        &payload_buffer,
        nonce,
        "-invalid",
    );
    var invalid_buffer: [wire_size_max]u8 = undefined;
    const invalid = try makeInvalidPacket(
        .rsv1,
        &invalid_buffer,
        target,
        invalid_payload,
    );
    try sendDatagram(io, first_fd, invalid, relay, deadline);
    try expectNoResponsePair(
        io,
        first_fd,
        second_fd,
        deadline.limited(io, absence_window_ms),
    );

    const pinned_payload = try taggedPayload(
        &payload_buffer,
        nonce,
        "-pinned",
    );
    try sendAndExpectIpv4(
        io,
        second_fd,
        relay,
        target,
        pinned_payload,
        deadline,
    );

    const wrong_source_payload = try taggedPayload(
        &payload_buffer,
        nonce,
        "-wrong-source",
    );
    var valid_buffer: [wire_size_max]u8 = undefined;
    const valid = try buildSocksUdpIpv4(
        &valid_buffer,
        target,
        wrong_source_payload,
    );
    try sendDatagram(io, first_fd, valid, relay, deadline);
    try expectNoResponsePair(
        io,
        first_fd,
        second_fd,
        deadline.limited(io, absence_window_ms),
    );

    try sendAndExpectIpv4(
        io,
        second_fd,
        relay,
        target,
        nonce,
        deadline,
    );
}

fn probeClientIp(
    io: std.Io,
    mixed_port: u16,
    target_port: u16,
    nonce: []const u8,
    deadline: Deadline,
) !void {
    const association = try openAssociation(io, mixed_port, deadline);
    defer closeFd(association.fd);
    const relay = association.relay.?;
    const wrong_ip_fd = try createUdpSocketAt(
        try discoverNonLoopbackIpv4(),
        0,
    );
    defer closeFd(wrong_ip_fd);
    const right_ip_fd = try createUdpSocket(0);
    defer closeFd(right_ip_fd);
    const target = Endpoint4{
        .ip = .{ 127, 0, 0, 1 },
        .port = target_port,
    };
    var request_buffer: [wire_size_max]u8 = undefined;
    const request = try buildSocksUdpIpv4(
        &request_buffer,
        target,
        nonce,
    );
    try sendDatagram(io, wrong_ip_fd, request, relay, deadline);
    try expectNoResponsePair(
        io,
        wrong_ip_fd,
        right_ip_fd,
        deadline.limited(io, absence_window_ms),
    );
    try sendAndExpectIpv4(
        io,
        right_ip_fd,
        relay,
        target,
        nonce,
        deadline,
    );
}

fn probeControlClose(
    io: std.Io,
    mixed_port: u16,
    target_port: u16,
    nonce: []const u8,
    deadline: Deadline,
) !void {
    var association = try openAssociation(io, mixed_port, deadline);
    defer if (association.fd >= 0) closeFd(association.fd);
    const old_relay = association.relay.?;
    const udp_fd = try createUdpSocket(0);
    defer closeFd(udp_fd);
    const target = Endpoint4{
        .ip = .{ 127, 0, 0, 1 },
        .port = target_port,
    };
    var payload_buffer: [tagged_payload_size_max]u8 = undefined;
    const before_close_payload = try taggedPayload(
        &payload_buffer,
        nonce,
        "-before-close",
    );
    try sendAndExpectIpv4(
        io,
        udp_fd,
        old_relay,
        target,
        before_close_payload,
        deadline,
    );

    try completeControlTeardown(io, &association.fd, deadline);
    const closed_payload = try taggedPayload(
        &payload_buffer,
        nonce,
        "-closed",
    );
    var request_buffer: [wire_size_max]u8 = undefined;
    const request = try buildSocksUdpIpv4(
        &request_buffer,
        target,
        closed_payload,
    );
    try sendDatagram(io, udp_fd, request, old_relay, deadline);
    try expectNoResponse(
        io,
        udp_fd,
        deadline.limited(io, absence_window_ms),
    );

    const recovery = try openAssociation(io, mixed_port, deadline);
    defer closeFd(recovery.fd);
    const recovery_udp_fd = try createUdpSocket(0);
    defer closeFd(recovery_udp_fd);
    try sendAndExpectIpv4(
        io,
        recovery_udp_fd,
        recovery.relay.?,
        target,
        nonce,
        deadline,
    );
}

fn probeSelectionTeardown(
    io: std.Io,
    mixed_port: u16,
    target_port: u16,
    nonce: []const u8,
    deadline: Deadline,
) !void {
    var association = try openAssociation(io, mixed_port, deadline);
    defer if (association.fd >= 0) closeFd(association.fd);
    const udp_fd = try createUdpSocket(0);
    defer closeFd(udp_fd);
    var request_buffer: [wire_size_max]u8 = undefined;
    const request = try buildSocksUdpIpv4(
        &request_buffer,
        .{ .ip = .{ 127, 0, 0, 1 }, .port = target_port },
        nonce,
    );
    try sendDatagram(
        io,
        udp_fd,
        request,
        association.relay.?,
        deadline,
    );
    try waitForControlEof(
        io,
        association.fd,
        deadline.limited(io, teardown_window_ms),
    );
    closeFd(association.fd);
    association.fd = -1;
    try expectNoResponse(
        io,
        udp_fd,
        deadline.limited(io, absence_window_ms),
    );
}

fn probeAssociateRejected(
    io: std.Io,
    mixed_port: u16,
    expected_reply: u8,
    deadline: Deadline,
) !void {
    const result = try establishAssociation(io, mixed_port, deadline);
    defer closeFd(result.fd);
    if (result.rep != expected_reply or result.relay != null) {
        return error.UnexpectedAssociateReply;
    }
}

fn fillPattern(output: []u8, pattern: []const u8) void {
    std.debug.assert(pattern.len > 0);
    for (output, 0..) |*byte, index| {
        byte.* = pattern[index % pattern.len];
    }
}

fn probeMax(
    io: std.Io,
    cipher: Cipher,
    mixed_port: u16,
    target_port: u16,
    nonce: []const u8,
    deadline: Deadline,
) !void {
    const association = try openAssociation(io, mixed_port, deadline);
    defer closeFd(association.fd);
    const relay = association.relay.?;
    const udp_fd = try createUdpSocket(0);
    defer closeFd(udp_fd);

    var domain: [domain_size_max]u8 = @splat('a');
    const payload_len_max = wire_size_max - cipher.saltLen() -
        tag_size - address_size_max;
    var payload_storage: [wire_size_max]u8 = undefined;
    fillPattern(payload_storage[0 .. payload_len_max + 1], nonce);
    var request_buffer: [wire_size_max]u8 = undefined;
    const exact_request = try buildSocksUdpDomain(
        &request_buffer,
        &domain,
        target_port,
        payload_storage[0..payload_len_max],
    );
    try sendDatagram(io, udp_fd, exact_request, relay, deadline);
    var response_buffer: [receive_size_max]u8 = undefined;
    const exact_response = try receiveRelayResponse(
        io,
        udp_fd,
        &response_buffer,
        deadline,
    );
    try validateDomainRelayResponse(
        exact_response,
        relay,
        &response_buffer,
        &domain,
        target_port,
        payload_storage[0..payload_len_max],
    );

    const oversized_request = try buildSocksUdpDomain(
        &request_buffer,
        &domain,
        target_port,
        payload_storage[0 .. payload_len_max + 1],
    );
    try sendDatagram(io, udp_fd, oversized_request, relay, deadline);
    try expectNoResponse(
        io,
        udp_fd,
        deadline.limited(io, absence_window_ms),
    );

    const recovery_request = try buildSocksUdpDomain(
        &request_buffer,
        &domain,
        target_port,
        nonce,
    );
    try sendDatagram(io, udp_fd, recovery_request, relay, deadline);
    const recovery_response = try receiveRelayResponse(
        io,
        udp_fd,
        &response_buffer,
        deadline,
    );
    try validateDomainRelayResponse(
        recovery_response,
        relay,
        &response_buffer,
        &domain,
        target_port,
        nonce,
    );
}

fn probeCapacity(
    io: std.Io,
    mixed_port: u16,
    deadline: Deadline,
) !void {
    var control_fds: [association_count_max]std.posix.fd_t =
        @splat(-1);
    defer {
        for (control_fds) |fd| closeFd(fd);
    }

    for (&control_fds) |*fd| {
        const association = try openAssociation(io, mixed_port, deadline);
        fd.* = association.fd;
    }

    const rejected = try establishAssociation(io, mixed_port, deadline);
    defer closeFd(rejected.fd);
    if (rejected.rep != 0x01) return error.UnexpectedCapacityReply;

    try completeControlTeardown(io, &control_fds[0], deadline);
    for (0..syscall_retry_max) |_| {
        const candidate = try establishAssociation(io, mixed_port, deadline);
        if (candidate.rep == 0) {
            if (candidate.relay == null) {
                closeFd(candidate.fd);
                return error.InvalidAssociateReply;
            }
            control_fds[0] = candidate.fd;
            return;
        }
        closeFd(candidate.fd);
        if (candidate.rep != 0x01) return error.UnexpectedCapacityReply;
        const remaining_ms = deadline.remaining(io) catch
            return error.CapacitySlotNotReleased;
        try std.Io.sleep(
            io,
            .fromMilliseconds(@intCast(@min(remaining_ms, 5))),
            .awake,
        );
    }
    return error.CapacitySlotNotReleased;
}
